package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * DepartmentInformations generated by hbm2java
 */
public class DepartmentInformations implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer parentDepartmentId;
	private String description;
	private Integer layer;
	private Integer managerId;
	private Integer viceManagerId;
	private String duty;
	private Date createdAt;
	private Date updatedAt;

	public DepartmentInformations() {
	}

	public DepartmentInformations(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public DepartmentInformations(String name, Integer parentDepartmentId, String description, Integer layer,
			Integer managerId, Integer viceManagerId, String duty, Date createdAt, Date updatedAt) {
		this.name = name;
		this.parentDepartmentId = parentDepartmentId;
		this.description = description;
		this.layer = layer;
		this.managerId = managerId;
		this.viceManagerId = viceManagerId;
		this.duty = duty;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getParentDepartmentId() {
		return this.parentDepartmentId;
	}

	public void setParentDepartmentId(Integer parentDepartmentId) {
		this.parentDepartmentId = parentDepartmentId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLayer() {
		return this.layer;
	}

	public void setLayer(Integer layer) {
		this.layer = layer;
	}

	public Integer getManagerId() {
		return this.managerId;
	}

	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	public Integer getViceManagerId() {
		return this.viceManagerId;
	}

	public void setViceManagerId(Integer viceManagerId) {
		this.viceManagerId = viceManagerId;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
