package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Packageinformation generated by hbm2java
 */
@Entity
@Table(name = "packageinformation", catalog = "isdsp_dev")
public class EnginePackageinformation implements java.io.Serializable {

	private Integer id;
	private int packageId;
	private String packageName;
	private String description;
	private String durationUnit;
	private Float costUnit;
	private Integer authorId;
	private Date createDate;
	private String goalOwluri;

	public EnginePackageinformation() {
	}

	public EnginePackageinformation(int packageId) {
		this.packageId = packageId;
	}

	public EnginePackageinformation(int packageId, String packageName, String description, String durationUnit,
			Float costUnit, Integer authorId, Date createDate, String goalOwluri) {
		this.packageId = packageId;
		this.packageName = packageName;
		this.description = description;
		this.durationUnit = durationUnit;
		this.costUnit = costUnit;
		this.authorId = authorId;
		this.createDate = createDate;
		this.goalOwluri = goalOwluri;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PackageID", nullable = false)
	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	@Column(name = "PackageName", length = 50)
	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	@Column(name = "Description", length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DurationUnit", length = 1)
	public String getDurationUnit() {
		return this.durationUnit;
	}

	public void setDurationUnit(String durationUnit) {
		this.durationUnit = durationUnit;
	}

	@Column(name = "CostUnit", precision = 12, scale = 0)
	public Float getCostUnit() {
		return this.costUnit;
	}

	public void setCostUnit(Float costUnit) {
		this.costUnit = costUnit;
	}

	@Column(name = "AuthorID")
	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "GoalOWLURI", length = 200)
	public String getGoalOwluri() {
		return this.goalOwluri;
	}

	public void setGoalOwluri(String goalOwluri) {
		this.goalOwluri = goalOwluri;
	}

}
