package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caseinformation generated by hbm2java
 */
@Entity
@Table(name = "caseinformation", catalog = "isdsp_dev")
public class EngineCaseinformation implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int workflowId;
	private String caseName;
	private String keyWords;
	private Integer initiatorId;
	private Date initiatorDate;

	public EngineCaseinformation() {
	}

	public EngineCaseinformation(String processId, int workflowId) {
		this.processId = processId;
		this.workflowId = workflowId;
	}

	public EngineCaseinformation(String processId, int workflowId, String caseName, String keyWords, Integer initiatorId,
			Date initiatorDate) {
		this.processId = processId;
		this.workflowId = workflowId;
		this.caseName = caseName;
		this.keyWords = keyWords;
		this.initiatorId = initiatorId;
		this.initiatorDate = initiatorDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "WorkflowID", nullable = false)
	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "CaseName", length = 50)
	public String getCaseName() {
		return this.caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	@Column(name = "KeyWords", length = 100)
	public String getKeyWords() {
		return this.keyWords;
	}

	public void setKeyWords(String keyWords) {
		this.keyWords = keyWords;
	}

	@Column(name = "InitiatorID")
	public Integer getInitiatorId() {
		return this.initiatorId;
	}

	public void setInitiatorId(Integer initiatorId) {
		this.initiatorId = initiatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InitiatorDate", length = 19)
	public Date getInitiatorDate() {
		return this.initiatorDate;
	}

	public void setInitiatorDate(Date initiatorDate) {
		this.initiatorDate = initiatorDate;
	}

}
