package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Processprocessecarule generated by hbm2java
 */
@Entity
@Table(name = "processprocessecarule", catalog = "isdsp_dev")
public class EngineProcessprocessecarule implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int ruleId;
	private int eventId;
	private int conditionId;
	private String actionExpression;
	private Float probability;
	private Float probabilityCoefficient;
	private Date activeTime;
	private Short repeatedTime;

	public EngineProcessprocessecarule() {
	}

	public EngineProcessprocessecarule(String processId, int ruleId, int eventId, int conditionId) {
		this.processId = processId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
	}

	public EngineProcessprocessecarule(String processId, int ruleId, int eventId, int conditionId, String actionExpression,
			Float probability, Float probabilityCoefficient, Date activeTime, Short repeatedTime) {
		this.processId = processId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
		this.actionExpression = actionExpression;
		this.probability = probability;
		this.probabilityCoefficient = probabilityCoefficient;
		this.activeTime = activeTime;
		this.repeatedTime = repeatedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "RuleID", nullable = false)
	public int getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	@Column(name = "EventID", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "ConditionID", nullable = false)
	public int getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(int conditionId) {
		this.conditionId = conditionId;
	}

	@Column(name = "ActionExpression", length = 200)
	public String getActionExpression() {
		return this.actionExpression;
	}

	public void setActionExpression(String actionExpression) {
		this.actionExpression = actionExpression;
	}

	@Column(name = "Probability", precision = 12, scale = 0)
	public Float getProbability() {
		return this.probability;
	}

	public void setProbability(Float probability) {
		this.probability = probability;
	}

	@Column(name = "ProbabilityCoefficient", precision = 12, scale = 0)
	public Float getProbabilityCoefficient() {
		return this.probabilityCoefficient;
	}

	public void setProbabilityCoefficient(Float probabilityCoefficient) {
		this.probabilityCoefficient = probabilityCoefficient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActiveTime", length = 19)
	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

	@Column(name = "RepeatedTime")
	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

}
