package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Workflowactivityinvokingapplication generated by hbm2java
 */
@Entity
@Table(name = "workflowactivityinvokingapplication", catalog = "isdsp_dev")
public class EngineWorkflowactivityinvokingapplication implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int activityId;
	private int applicationId;
	private Short invocationType;
	private Integer inputSchemaId;
	private Integer outputSchemaId;

	public EngineWorkflowactivityinvokingapplication() {
	}

	public EngineWorkflowactivityinvokingapplication(int workflowId, int activityId, int applicationId) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.applicationId = applicationId;
	}

	public EngineWorkflowactivityinvokingapplication(int workflowId, int activityId, int applicationId, Short invocationType,
			Integer inputSchemaId, Integer outputSchemaId) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.applicationId = applicationId;
		this.invocationType = invocationType;
		this.inputSchemaId = inputSchemaId;
		this.outputSchemaId = outputSchemaId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "WorkflowID", nullable = false)
	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "ActivityID", nullable = false)
	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	@Column(name = "ApplicationID", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "InvocationType")
	public Short getInvocationType() {
		return this.invocationType;
	}

	public void setInvocationType(Short invocationType) {
		this.invocationType = invocationType;
	}

	@Column(name = "InputSchemaID")
	public Integer getInputSchemaId() {
		return this.inputSchemaId;
	}

	public void setInputSchemaId(Integer inputSchemaId) {
		this.inputSchemaId = inputSchemaId;
	}

	@Column(name = "OutputSchemaID")
	public Integer getOutputSchemaId() {
		return this.outputSchemaId;
	}

	public void setOutputSchemaId(Integer outputSchemaId) {
		this.outputSchemaId = outputSchemaId;
	}

}
