package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Processapplication generated by hbm2java
 */
@Entity
@Table(name = "processapplication", catalog = "isdsp_dev")
public class EngineProcessapplication implements java.io.Serializable {

	private Integer id;
	private String processId;
	private short applicationId;
	private String description;

	public EngineProcessapplication() {
	}

	public EngineProcessapplication(String processId, short applicationId) {
		this.processId = processId;
		this.applicationId = applicationId;
	}

	public EngineProcessapplication(String processId, short applicationId, String description) {
		this.processId = processId;
		this.applicationId = applicationId;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "ApplicationID", nullable = false)
	public short getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(short applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
