package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Processflow generated by hbm2java
 */
@Entity
@Table(name = "processflow", catalog = "isdsp_dev")
public class EngineProcessflow implements java.io.Serializable {

	private Integer id;
	private short modelType;
	private String processId;
	private int flowId;
	private Integer parentId;
	private short type;
	private short fromObjectType;
	private int objectId1;
	private short toObjectType;
	private int objectId2;

	public EngineProcessflow() {
	}

	public EngineProcessflow(short modelType, String processId, int flowId, short type, short fromObjectType, int objectId1,
			short toObjectType, int objectId2) {
		this.modelType = modelType;
		this.processId = processId;
		this.flowId = flowId;
		this.type = type;
		this.fromObjectType = fromObjectType;
		this.objectId1 = objectId1;
		this.toObjectType = toObjectType;
		this.objectId2 = objectId2;
	}

	public EngineProcessflow(short modelType, String processId, int flowId, Integer parentId, short type,
			short fromObjectType, int objectId1, short toObjectType, int objectId2) {
		this.modelType = modelType;
		this.processId = processId;
		this.flowId = flowId;
		this.parentId = parentId;
		this.type = type;
		this.fromObjectType = fromObjectType;
		this.objectId1 = objectId1;
		this.toObjectType = toObjectType;
		this.objectId2 = objectId2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ModelType", nullable = false)
	public short getModelType() {
		return this.modelType;
	}

	public void setModelType(short modelType) {
		this.modelType = modelType;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "FlowID", nullable = false)
	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	@Column(name = "ParentID")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "Type", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	@Column(name = "FromObjectType", nullable = false)
	public short getFromObjectType() {
		return this.fromObjectType;
	}

	public void setFromObjectType(short fromObjectType) {
		this.fromObjectType = fromObjectType;
	}

	@Column(name = "ObjectId1", nullable = false)
	public int getObjectId1() {
		return this.objectId1;
	}

	public void setObjectId1(int objectId1) {
		this.objectId1 = objectId1;
	}

	@Column(name = "ToObjectType", nullable = false)
	public short getToObjectType() {
		return this.toObjectType;
	}

	public void setToObjectType(short toObjectType) {
		this.toObjectType = toObjectType;
	}

	@Column(name = "ObjectID2", nullable = false)
	public int getObjectId2() {
		return this.objectId2;
	}

	public void setObjectId2(int objectId2) {
		this.objectId2 = objectId2;
	}

}
