package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Processflowobjects generated by hbm2java
 */
@Entity
@Table(name = "processflowobjects", catalog = "isdsp_dev")
public class EngineProcessflowobject implements java.io.Serializable {

	private Integer id;
	private int droolsRuleId;
	private String processId;
	private int flowId;
	private int fromActivityId;
	private int toActivityId;
	private String xslto2m;
	private String xsltm2i;
	private Integer oxmlid;
	private Integer mxmlid;
	private Integer ixmlid;

	public EngineProcessflowobject() {
	}

	public EngineProcessflowobject(int droolsRuleId, String processId, int flowId, int fromActivityId, int toActivityId) {
		this.droolsRuleId = droolsRuleId;
		this.processId = processId;
		this.flowId = flowId;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
	}

	public EngineProcessflowobject(int droolsRuleId, String processId, int flowId, int fromActivityId, int toActivityId,
			String xslto2m, String xsltm2i, Integer oxmlid, Integer mxmlid, Integer ixmlid) {
		this.droolsRuleId = droolsRuleId;
		this.processId = processId;
		this.flowId = flowId;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
		this.xslto2m = xslto2m;
		this.xsltm2i = xsltm2i;
		this.oxmlid = oxmlid;
		this.mxmlid = mxmlid;
		this.ixmlid = ixmlid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "DroolsRuleID", nullable = false)
	public int getDroolsRuleId() {
		return this.droolsRuleId;
	}

	public void setDroolsRuleId(int droolsRuleId) {
		this.droolsRuleId = droolsRuleId;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "FlowID", nullable = false)
	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	@Column(name = "FromActivityID", nullable = false)
	public int getFromActivityId() {
		return this.fromActivityId;
	}

	public void setFromActivityId(int fromActivityId) {
		this.fromActivityId = fromActivityId;
	}

	@Column(name = "ToActivityID", nullable = false)
	public int getToActivityId() {
		return this.toActivityId;
	}

	public void setToActivityId(int toActivityId) {
		this.toActivityId = toActivityId;
	}

	@Column(name = "XSLTO2M")
	public String getXslto2m() {
		return this.xslto2m;
	}

	public void setXslto2m(String xslto2m) {
		this.xslto2m = xslto2m;
	}

	@Column(name = "XSLTM2I")
	public String getXsltm2i() {
		return this.xsltm2i;
	}

	public void setXsltm2i(String xsltm2i) {
		this.xsltm2i = xsltm2i;
	}

	@Column(name = "OXMLID")
	public Integer getOxmlid() {
		return this.oxmlid;
	}

	public void setOxmlid(Integer oxmlid) {
		this.oxmlid = oxmlid;
	}

	@Column(name = "MXMLID")
	public Integer getMxmlid() {
		return this.mxmlid;
	}

	public void setMxmlid(Integer mxmlid) {
		this.mxmlid = mxmlid;
	}

	@Column(name = "IXMLID")
	public Integer getIxmlid() {
		return this.ixmlid;
	}

	public void setIxmlid(Integer ixmlid) {
		this.ixmlid = ixmlid;
	}

}
