package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Systemapplicationinformation generated by hbm2java
 */
@Entity
@Table(name = "systemapplicationinformation", catalog = "isdsp_dev")
public class EngineSystemapplicationinformation implements java.io.Serializable {

	private Integer id;
	private int applicationId;
	private String description;
	private String applicationName;
	private Short applicationType;
	private Integer inputSchemaId;
	private Integer outputSchemaId;

	public EngineSystemapplicationinformation() {
	}

	public EngineSystemapplicationinformation(int applicationId) {
		this.applicationId = applicationId;
	}

	public EngineSystemapplicationinformation(int applicationId, String description, String applicationName,
			Short applicationType, Integer inputSchemaId, Integer outputSchemaId) {
		this.applicationId = applicationId;
		this.description = description;
		this.applicationName = applicationName;
		this.applicationType = applicationType;
		this.inputSchemaId = inputSchemaId;
		this.outputSchemaId = outputSchemaId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ApplicationID", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ApplicationName", length = 100)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "ApplicationType")
	public Short getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationType(Short applicationType) {
		this.applicationType = applicationType;
	}

	@Column(name = "InputSchemaID")
	public Integer getInputSchemaId() {
		return this.inputSchemaId;
	}

	public void setInputSchemaId(Integer inputSchemaId) {
		this.inputSchemaId = inputSchemaId;
	}

	@Column(name = "OutputSchemaID")
	public Integer getOutputSchemaId() {
		return this.outputSchemaId;
	}

	public void setOutputSchemaId(Integer outputSchemaId) {
		this.outputSchemaId = outputSchemaId;
	}

}
