package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Workflowactivityinputmapping generated by hbm2java
 */
@Entity
@Table(name = "workflowactivityinputmapping", catalog = "isdsp_dev")
public class EngineWorkflowactivityinputmapping implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int activityId;
	private int dataflowId;
	private String inputSchema;
	private String inputXml;
	private String xslt;

	public EngineWorkflowactivityinputmapping() {
	}

	public EngineWorkflowactivityinputmapping(int workflowId, int activityId, int dataflowId) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.dataflowId = dataflowId;
	}

	public EngineWorkflowactivityinputmapping(int workflowId, int activityId, int dataflowId, String inputSchema,
			String inputXml, String xslt) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.dataflowId = dataflowId;
		this.inputSchema = inputSchema;
		this.inputXml = inputXml;
		this.xslt = xslt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "WorkflowID", nullable = false)
	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "ActivityID", nullable = false)
	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	@Column(name = "DataflowID", nullable = false)
	public int getDataflowId() {
		return this.dataflowId;
	}

	public void setDataflowId(int dataflowId) {
		this.dataflowId = dataflowId;
	}

	@Column(name = "InputSchema", length = 16777215)
	public String getInputSchema() {
		return this.inputSchema;
	}

	public void setInputSchema(String inputSchema) {
		this.inputSchema = inputSchema;
	}

	@Column(name = "InputXML", length = 16777215)
	public String getInputXml() {
		return this.inputXml;
	}

	public void setInputXml(String inputXml) {
		this.inputXml = inputXml;
	}

	@Column(name = "XSLT", length = 16777215)
	public String getXslt() {
		return this.xslt;
	}

	public void setXslt(String xslt) {
		this.xslt = xslt;
	}

}
