package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * HomelandNodes generated by hbm2java
 */
public class HomelandNodes implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private String color;
	private int sort;
	private int topicsCount;
	private Date createdAt;
	private Date updatedAt;
	private Integer wikiPageId;

	public HomelandNodes() {
	}

	public HomelandNodes(String name, int sort, int topicsCount, Date createdAt, Date updatedAt) {
		this.name = name;
		this.sort = sort;
		this.topicsCount = topicsCount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public HomelandNodes(String name, String description, String color, int sort, int topicsCount, Date createdAt,
			Date updatedAt, Integer wikiPageId) {
		this.name = name;
		this.description = description;
		this.color = color;
		this.sort = sort;
		this.topicsCount = topicsCount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.wikiPageId = wikiPageId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	public int getTopicsCount() {
		return this.topicsCount;
	}

	public void setTopicsCount(int topicsCount) {
		this.topicsCount = topicsCount;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getWikiPageId() {
		return this.wikiPageId;
	}

	public void setWikiPageId(Integer wikiPageId) {
		this.wikiPageId = wikiPageId;
	}

}
