package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * HomelandReplies generated by hbm2java
 */
public class HomelandReplies implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer topicId;
	private String body;
	private String bodyHtml;
	private Date deletedAt;
	private Date createdAt;
	private Date updatedAt;
	private Integer replyToId;

	public HomelandReplies() {
	}

	public HomelandReplies(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public HomelandReplies(Integer userId, Integer topicId, String body, String bodyHtml, Date deletedAt,
			Date createdAt, Date updatedAt, Integer replyToId) {
		this.userId = userId;
		this.topicId = topicId;
		this.body = body;
		this.bodyHtml = bodyHtml;
		this.deletedAt = deletedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.replyToId = replyToId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getBodyHtml() {
		return this.bodyHtml;
	}

	public void setBodyHtml(String bodyHtml) {
		this.bodyHtml = bodyHtml;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getReplyToId() {
		return this.replyToId;
	}

	public void setReplyToId(Integer replyToId) {
		this.replyToId = replyToId;
	}

}
