package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * HomelandTopics generated by hbm2java
 */
public class HomelandTopics implements java.io.Serializable {

	private Integer id;
	private int nodeId;
	private int userId;
	private String title;
	private String body;
	private String bodyHtml;
	private Integer lastReplyId;
	private Integer lastReplyUserId;
	private int lastActiveMark;
	private Date repliedAt;
	private int repliesCount;
	private Date deletedAt;
	private Date createdAt;
	private Date updatedAt;

	public HomelandTopics() {
	}

	public HomelandTopics(int nodeId, int userId, String title, int lastActiveMark, int repliesCount, Date createdAt,
			Date updatedAt) {
		this.nodeId = nodeId;
		this.userId = userId;
		this.title = title;
		this.lastActiveMark = lastActiveMark;
		this.repliesCount = repliesCount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public HomelandTopics(int nodeId, int userId, String title, String body, String bodyHtml, Integer lastReplyId,
			Integer lastReplyUserId, int lastActiveMark, Date repliedAt, int repliesCount, Date deletedAt,
			Date createdAt, Date updatedAt) {
		this.nodeId = nodeId;
		this.userId = userId;
		this.title = title;
		this.body = body;
		this.bodyHtml = bodyHtml;
		this.lastReplyId = lastReplyId;
		this.lastReplyUserId = lastReplyUserId;
		this.lastActiveMark = lastActiveMark;
		this.repliedAt = repliedAt;
		this.repliesCount = repliesCount;
		this.deletedAt = deletedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(int nodeId) {
		this.nodeId = nodeId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getBodyHtml() {
		return this.bodyHtml;
	}

	public void setBodyHtml(String bodyHtml) {
		this.bodyHtml = bodyHtml;
	}

	public Integer getLastReplyId() {
		return this.lastReplyId;
	}

	public void setLastReplyId(Integer lastReplyId) {
		this.lastReplyId = lastReplyId;
	}

	public Integer getLastReplyUserId() {
		return this.lastReplyUserId;
	}

	public void setLastReplyUserId(Integer lastReplyUserId) {
		this.lastReplyUserId = lastReplyUserId;
	}

	public int getLastActiveMark() {
		return this.lastActiveMark;
	}

	public void setLastActiveMark(int lastActiveMark) {
		this.lastActiveMark = lastActiveMark;
	}

	public Date getRepliedAt() {
		return this.repliedAt;
	}

	public void setRepliedAt(Date repliedAt) {
		this.repliedAt = repliedAt;
	}

	public int getRepliesCount() {
		return this.repliesCount;
	}

	public void setRepliesCount(int repliesCount) {
		this.repliesCount = repliesCount;
	}

	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
