package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Javaclassmethod generated by hbm2java
 */
public class Javaclassmethod implements java.io.Serializable {

	private Integer id;
	private int applicationId;
	private String className;
	private String classUrl;
	private String methodName;
	private String userName;
	private String password;
	private Integer inputSchemaId;
	private Integer outputSchemaId;
	private Integer inputXmlid;
	private Integer outputXmlid;

	public Javaclassmethod() {
	}

	public Javaclassmethod(int applicationId) {
		this.applicationId = applicationId;
	}

	public Javaclassmethod(int applicationId, String className, String classUrl, String methodName, String userName,
			String password, Integer inputSchemaId, Integer outputSchemaId, Integer inputXmlid, Integer outputXmlid) {
		this.applicationId = applicationId;
		this.className = className;
		this.classUrl = classUrl;
		this.methodName = methodName;
		this.userName = userName;
		this.password = password;
		this.inputSchemaId = inputSchemaId;
		this.outputSchemaId = outputSchemaId;
		this.inputXmlid = inputXmlid;
		this.outputXmlid = outputXmlid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getClassUrl() {
		return this.classUrl;
	}

	public void setClassUrl(String classUrl) {
		this.classUrl = classUrl;
	}

	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getInputSchemaId() {
		return this.inputSchemaId;
	}

	public void setInputSchemaId(Integer inputSchemaId) {
		this.inputSchemaId = inputSchemaId;
	}

	public Integer getOutputSchemaId() {
		return this.outputSchemaId;
	}

	public void setOutputSchemaId(Integer outputSchemaId) {
		this.outputSchemaId = outputSchemaId;
	}

	public Integer getInputXmlid() {
		return this.inputXmlid;
	}

	public void setInputXmlid(Integer inputXmlid) {
		this.inputXmlid = inputXmlid;
	}

	public Integer getOutputXmlid() {
		return this.outputXmlid;
	}

	public void setOutputXmlid(Integer outputXmlid) {
		this.outputXmlid = outputXmlid;
	}

}
