package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NodeOptions generated by hbm2java
 */
@Entity
@Table(name = "node_options", catalog = "isdsp_dev")
public class NodeOption implements java.io.Serializable {

	private Integer id;
	private NodeFunction nodeFunction;
	private NodeOptionType nodeOptionType;
	private Integer nodeIndex;
	private String name;
	private String label;
	private String description;
	private String defaultValue;
	private Date createdAt;
	private Date updatedAt;
	private Set<NodeOptionChoice> nodeOptionChoices = new HashSet<NodeOptionChoice>(0);
	private Set<NodeOptionValue> nodeOptionValues = new HashSet<NodeOptionValue>(0);
	
	public NodeOption() {
	}

	public NodeOption(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeOption(NodeFunction nodeFunctions, NodeOptionType nodeOptionTypes, Integer nodeIndex, String name,
			String label, String description, String defaultValue, Date createdAt, Date updatedAt,
			Set<NodeOptionChoice> nodeOptionChoiceses, Set<NodeOptionValue> nodeOptionValueses) {
		this.nodeFunction = nodeFunctions;
		this.nodeOptionType = nodeOptionTypes;
		this.nodeIndex = nodeIndex;
		this.name = name;
		this.label = label;
		this.description = description;
		this.defaultValue = defaultValue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptionChoices = nodeOptionChoiceses;
		this.nodeOptionValues = nodeOptionValueses;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node_function_id")
	public NodeFunction getNodeFunction() {
		return this.nodeFunction;
	}

	public void setNodeFunction(NodeFunction nodeFunctions) {
		this.nodeFunction = nodeFunctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node_option_type_id")
	public NodeOptionType getNodeOptionType() {
		return this.nodeOptionType;
	}

	public void setNodeOptionType(NodeOptionType nodeOptionTypes) {
		this.nodeOptionType = nodeOptionTypes;
	}

	@Column(name = "node_index")
	public Integer getNodeIndex() {
		return this.nodeIndex;
	}

	public void setNodeIndex(Integer nodeIndex) {
		this.nodeIndex = nodeIndex;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "label", length = 65535)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "default_value", length = 65535)
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeOption")
	public Set<NodeOptionChoice> getNodeOptionChoices() {
		return this.nodeOptionChoices;
	}

	public void setNodeOptionChoices(Set<NodeOptionChoice> nodeOptionChoiceses) {
		this.nodeOptionChoices = nodeOptionChoiceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeOption")
	public Set<NodeOptionValue> getNodeOptionValues() {
		return this.nodeOptionValues;
	}

	public void setNodeOptionValues(Set<NodeOptionValue> nodeOptionValueses) {
		this.nodeOptionValues = nodeOptionValueses;
	}

	
}
