package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NodeInformations generated by hbm2java
 */
@Entity
@Table(name = "node_informations", catalog = "isdsp_dev")
public class NodeInformation implements java.io.Serializable {

	private Integer id;
	private NodeFunction nodeFunctions;
	private WorkflowInformation workflowInformations;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set<NodeOptionValue> nodeOptionValueses = new HashSet<NodeOptionValue>(0);
	private Set<NodeOptionValue> nodeOptionValueses_1 = new HashSet<NodeOptionValue>(0);

	public NodeInformation() {
	}

	public NodeInformation(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeInformation(NodeFunction nodeFunctions, WorkflowInformation workflowInformations, String name,
			Date createdAt, Date updatedAt, Set<NodeOptionValue> nodeOptionValueses,
			Set<NodeOptionValue> nodeOptionValueses_1) {
		this.nodeFunctions = nodeFunctions;
		this.workflowInformations = workflowInformations;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptionValueses = nodeOptionValueses;
		this.nodeOptionValueses_1 = nodeOptionValueses_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node_function_id")
	public NodeFunction getNodeFunctions() {
		return this.nodeFunctions;
	}

	public void setNodeFunctions(NodeFunction nodeFunctions) {
		this.nodeFunctions = nodeFunctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workflow_information_id")
	public WorkflowInformation getWorkflowInformations() {
		return this.workflowInformations;
	}

	public void setWorkflowInformations(WorkflowInformation workflowInformations) {
		this.workflowInformations = workflowInformations;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeInformations")
	public Set<NodeOptionValue> getNodeOptionValueses() {
		return this.nodeOptionValueses;
	}

	public void setNodeOptionValueses(Set<NodeOptionValue> nodeOptionValueses) {
		this.nodeOptionValueses = nodeOptionValueses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeInformations")
	public Set<NodeOptionValue> getNodeOptionValueses_1() {
		return this.nodeOptionValueses_1;
	}

	public void setNodeOptionValueses_1(Set<NodeOptionValue> nodeOptionValueses_1) {
		this.nodeOptionValueses_1 = nodeOptionValueses_1;
	}

}
