package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeCategories generated by hbm2java
 */
public class NodeCategories implements java.io.Serializable {

	private Integer id;
	private NodeTypes nodeTypes;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set nodeFunctionses = new HashSet(0);

	public NodeCategories() {
	}

	public NodeCategories(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeCategories(NodeTypes nodeTypes, String name, Date createdAt, Date updatedAt, Set nodeFunctionses) {
		this.nodeTypes = nodeTypes;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeFunctionses = nodeFunctionses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public NodeTypes getNodeTypes() {
		return this.nodeTypes;
	}

	public void setNodeTypes(NodeTypes nodeTypes) {
		this.nodeTypes = nodeTypes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getNodeFunctionses() {
		return this.nodeFunctionses;
	}

	public void setNodeFunctionses(Set nodeFunctionses) {
		this.nodeFunctionses = nodeFunctionses;
	}

}
