package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NodeOptionTypes generated by hbm2java
 */
@Entity
@Table(name = "node_option_types", catalog = "isdsp_dev")
public class NodeOptionType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set<NodeOption> nodeOptions = new HashSet<NodeOption>(0);
	

	public NodeOptionType() {
	}

	public NodeOptionType(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeOptionType(String name, Date createdAt, Date updatedAt, Set<NodeOption> nodeOptionses
) {
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptions = nodeOptionses;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeOptionType")
	public Set<NodeOption> getNodeOptions() {
		return this.nodeOptions;
	}

	public void setNodeOptions(Set<NodeOption> nodeOptionses) {
		this.nodeOptions = nodeOptionses;
	}

}
