package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NodeInformations generated by hbm2java
 */
@Entity
@Table(name = "node_informations", catalog = "isdsp_dev")
public class NodeInformation implements java.io.Serializable {

	private Integer id;
	private NodeFunction nodeFunction;
	private WorkflowInformation workflowInformation;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set<NodeOptionValue> nodeOptionValues = new HashSet<NodeOptionValue>(0);

	public NodeInformation() {
	}

	public NodeInformation(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeInformation(NodeFunction nodeFunctions, WorkflowInformation workflowInformations, String name,
			Date createdAt, Date updatedAt, Set<NodeOptionValue> nodeOptionValueses) {
		this.nodeFunction = nodeFunctions;
		this.workflowInformation = workflowInformations;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptionValues = nodeOptionValueses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node_function_id")
	public NodeFunction getNodeFunction() {
		return this.nodeFunction;
	}

	public void setNodeFunction(NodeFunction nodeFunctions) {
		this.nodeFunction = nodeFunctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workflow_information_id")
	public WorkflowInformation getWorkflowInformation() {
		return this.workflowInformation;
	}

	public void setWorkflowInformation(WorkflowInformation workflowInformations) {
		this.workflowInformation = workflowInformations;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeInformation")
	public Set<NodeOptionValue> getNodeOptionValues() {
		return this.nodeOptionValues;
	}

	public void setNodeOptionValues(Set<NodeOptionValue> nodeOptionValueses) {
		this.nodeOptionValues = nodeOptionValueses;
	}

	

}
