package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeInformations generated by hbm2java
 */
public class NodeInformations implements java.io.Serializable {

	private Integer id;
	private NodeFunctions nodeFunctions;
	private WorkflowInformations workflowInformations;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set nodeOptionValueses = new HashSet(0);

	public NodeInformations() {
	}

	public NodeInformations(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeInformations(NodeFunctions nodeFunctions, WorkflowInformations workflowInformations, String name,
			Date createdAt, Date updatedAt, Set nodeOptionValueses) {
		this.nodeFunctions = nodeFunctions;
		this.workflowInformations = workflowInformations;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptionValueses = nodeOptionValueses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public NodeFunctions getNodeFunctions() {
		return this.nodeFunctions;
	}

	public void setNodeFunctions(NodeFunctions nodeFunctions) {
		this.nodeFunctions = nodeFunctions;
	}

	public WorkflowInformations getWorkflowInformations() {
		return this.workflowInformations;
	}

	public void setWorkflowInformations(WorkflowInformations workflowInformations) {
		this.workflowInformations = workflowInformations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getNodeOptionValueses() {
		return this.nodeOptionValueses;
	}

	public void setNodeOptionValueses(Set nodeOptionValueses) {
		this.nodeOptionValueses = nodeOptionValueses;
	}

}
