package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NodeInformations generated by hbm2java
 */
@Entity
@Table(name = "node_process_informations", catalog = "isdsp_dev")
public class NodeProcessInformation implements java.io.Serializable {

	private Integer id;
	private NodeFunction nodeFunction;
	private ProcessInformation processInformation;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set<NodeProcessOptionValue> nodeProcessOptionValues = new HashSet<NodeProcessOptionValue>(0);

	public NodeProcessInformation() {
	}

	public NodeProcessInformation(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}



	public NodeProcessInformation(NodeFunction nodeFunction,
			String name, Date createdAt, Date updatedAt) {
		this.nodeFunction = nodeFunction;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node_function_id")
	public NodeFunction getNodeFunction() {
		return this.nodeFunction;
	}

	public void setNodeFunction(NodeFunction nodeFunctions) {
		this.nodeFunction = nodeFunctions;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "process_information_id")
	public ProcessInformation getProcessInformation() {
		return processInformation;
	}

	public void setProcessInformation(ProcessInformation processInformation) {
		this.processInformation = processInformation;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}


	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeProcessInformation")
	public Set<NodeProcessOptionValue> getNodeProcessOptionValues() {
		return nodeProcessOptionValues;
	}

	public void setNodeProcessOptionValues(Set<NodeProcessOptionValue> nodeProcessOptionValues) {
		this.nodeProcessOptionValues = nodeProcessOptionValues;
	}


	
	@Override
	public String toString() {
		return "NodeProcessInformation [id=" + id + ", nodeFunction=" + nodeFunction + ", processInformation="
				+ processInformation + ", name=" + name + ", nodeProcessOptionValues=" + nodeProcessOptionValues + "]";
	}

	

}
