package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeFunctions generated by hbm2java
 */
public class NodeFunctions implements java.io.Serializable {

	private Integer id;
	private NodeCategories nodeCategories;
	private NodeTypes nodeTypes;
	private String name;
	private String description;
	private Date createdAt;
	private Date updatedAt;
	private Set nodeOptionses = new HashSet(0);
	private Set nodeInformationses = new HashSet(0);

	public NodeFunctions() {
	}

	public NodeFunctions(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeFunctions(NodeCategories nodeCategories, NodeTypes nodeTypes, String name, String description,
			Date createdAt, Date updatedAt, Set nodeOptionses, Set nodeInformationses) {
		this.nodeCategories = nodeCategories;
		this.nodeTypes = nodeTypes;
		this.name = name;
		this.description = description;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptionses = nodeOptionses;
		this.nodeInformationses = nodeInformationses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public NodeCategories getNodeCategories() {
		return this.nodeCategories;
	}

	public void setNodeCategories(NodeCategories nodeCategories) {
		this.nodeCategories = nodeCategories;
	}

	public NodeTypes getNodeTypes() {
		return this.nodeTypes;
	}

	public void setNodeTypes(NodeTypes nodeTypes) {
		this.nodeTypes = nodeTypes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getNodeOptionses() {
		return this.nodeOptionses;
	}

	public void setNodeOptionses(Set nodeOptionses) {
		this.nodeOptionses = nodeOptionses;
	}

	public Set getNodeInformationses() {
		return this.nodeInformationses;
	}

	public void setNodeInformationses(Set nodeInformationses) {
		this.nodeInformationses = nodeInformationses;
	}

}
