package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeOptions generated by hbm2java
 */
public class NodeOptions implements java.io.Serializable {

	private Integer id;
	private NodeFunctions nodeFunctions;
	private NodeOptionTypes nodeOptionTypes;
	private Integer nodeIndex;
	private String name;
	private String label;
	private String description;
	private String defaultValue;
	private Date createdAt;
	private Date updatedAt;
	private Set nodeOptionChoiceses = new HashSet(0);
	private Set nodeOptionValueses = new HashSet(0);

	public NodeOptions() {
	}

	public NodeOptions(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeOptions(NodeFunctions nodeFunctions, NodeOptionTypes nodeOptionTypes, Integer nodeIndex, String name,
			String label, String description, String defaultValue, Date createdAt, Date updatedAt,
			Set nodeOptionChoiceses, Set nodeOptionValueses) {
		this.nodeFunctions = nodeFunctions;
		this.nodeOptionTypes = nodeOptionTypes;
		this.nodeIndex = nodeIndex;
		this.name = name;
		this.label = label;
		this.description = description;
		this.defaultValue = defaultValue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptionChoiceses = nodeOptionChoiceses;
		this.nodeOptionValueses = nodeOptionValueses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public NodeFunctions getNodeFunctions() {
		return this.nodeFunctions;
	}

	public void setNodeFunctions(NodeFunctions nodeFunctions) {
		this.nodeFunctions = nodeFunctions;
	}

	public NodeOptionTypes getNodeOptionTypes() {
		return this.nodeOptionTypes;
	}

	public void setNodeOptionTypes(NodeOptionTypes nodeOptionTypes) {
		this.nodeOptionTypes = nodeOptionTypes;
	}

	public Integer getNodeIndex() {
		return this.nodeIndex;
	}

	public void setNodeIndex(Integer nodeIndex) {
		this.nodeIndex = nodeIndex;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getNodeOptionChoiceses() {
		return this.nodeOptionChoiceses;
	}

	public void setNodeOptionChoiceses(Set nodeOptionChoiceses) {
		this.nodeOptionChoiceses = nodeOptionChoiceses;
	}

	public Set getNodeOptionValueses() {
		return this.nodeOptionValueses;
	}

	public void setNodeOptionValueses(Set nodeOptionValueses) {
		this.nodeOptionValueses = nodeOptionValueses;
	}

}
