package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeOptionTypes generated by hbm2java
 */
public class NodeOptionTypes implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set nodeOptionses = new HashSet(0);

	public NodeOptionTypes() {
	}

	public NodeOptionTypes(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public NodeOptionTypes(String name, Date createdAt, Date updatedAt, Set nodeOptionses) {
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.nodeOptionses = nodeOptionses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getNodeOptionses() {
		return this.nodeOptionses;
	}

	public void setNodeOptionses(Set nodeOptionses) {
		this.nodeOptionses = nodeOptionses;
	}

}
