package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Packageinformation generated by hbm2java
 */
public class Packageinformation implements java.io.Serializable {

	private Integer id;
	private int packageId;
	private String packageName;
	private String description;
	private String durationUnit;
	private Float costUnit;
	private Integer authorId;
	private Date createDate;
	private String goalOwluri;

	public Packageinformation() {
	}

	public Packageinformation(int packageId) {
		this.packageId = packageId;
	}

	public Packageinformation(int packageId, String packageName, String description, String durationUnit,
			Float costUnit, Integer authorId, Date createDate, String goalOwluri) {
		this.packageId = packageId;
		this.packageName = packageName;
		this.description = description;
		this.durationUnit = durationUnit;
		this.costUnit = costUnit;
		this.authorId = authorId;
		this.createDate = createDate;
		this.goalOwluri = goalOwluri;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDurationUnit() {
		return this.durationUnit;
	}

	public void setDurationUnit(String durationUnit) {
		this.durationUnit = durationUnit;
	}

	public Float getCostUnit() {
		return this.costUnit;
	}

	public void setCostUnit(Float costUnit) {
		this.costUnit = costUnit;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getGoalOwluri() {
		return this.goalOwluri;
	}

	public void setGoalOwluri(String goalOwluri) {
		this.goalOwluri = goalOwluri;
	}

}
