package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * PersonInformations generated by hbm2java
 */
public class PersonInformations implements java.io.Serializable {

	private Integer id;
	private String personName;
	private String userName;
	private String gender;
	private Date birthday;
	private String description;
	private String phoneNumber;
	private String email;
	private String technicalPost;
	private Integer state;
	private String password;
	private Date createdAt;
	private Date updatedAt;

	public PersonInformations() {
	}

	public PersonInformations(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public PersonInformations(String personName, String userName, String gender, Date birthday, String description,
			String phoneNumber, String email, String technicalPost, Integer state, String password, Date createdAt,
			Date updatedAt) {
		this.personName = personName;
		this.userName = userName;
		this.gender = gender;
		this.birthday = birthday;
		this.description = description;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.technicalPost = technicalPost;
		this.state = state;
		this.password = password;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTechnicalPost() {
		return this.technicalPost;
	}

	public void setTechnicalPost(String technicalPost) {
		this.technicalPost = technicalPost;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
