package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processcontrolflowcondition generated by hbm2java
 */
public class Processcontrolflowcondition implements java.io.Serializable {

	private Integer id;
	private String processId;
	private short controlFlowId;
	private short conditionId;

	public Processcontrolflowcondition() {
	}

	public Processcontrolflowcondition(String processId, short controlFlowId, short conditionId) {
		this.processId = processId;
		this.controlFlowId = controlFlowId;
		this.conditionId = conditionId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public short getControlFlowId() {
		return this.controlFlowId;
	}

	public void setControlFlowId(short controlFlowId) {
		this.controlFlowId = controlFlowId;
	}

	public short getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(short conditionId) {
		this.conditionId = conditionId;
	}

}
