package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessInformations generated by hbm2java
 */
public class ProcessInformations implements java.io.Serializable {

	private Integer id;
	private Integer workflowInformationId;
	private String name;
	private String description;
	private Integer createrId;
	private Integer userId;
	private Boolean isShared;
	private Integer parentCaseId;
	private Boolean persistent;
	private String state;
	private Integer caseType;
	private Date createdAt;
	private Date updatedAt;
	private String processType;
	private Integer processId;
	private Set processFileses = new HashSet(0);
	private Set downloadFileses = new HashSet(0);
	private Set uploadFileses = new HashSet(0);
	private Set processResultses = new HashSet(0);

	public ProcessInformations() {
	}

	public ProcessInformations(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProcessInformations(Integer workflowInformationId, String name, String description, Integer createrId,
			Integer userId, Boolean isShared, Integer parentCaseId, Boolean persistent, String state, Integer caseType,
			Date createdAt, Date updatedAt, String processType, Integer processId, Set processFileses,
			Set downloadFileses, Set uploadFileses, Set processResultses) {
		this.workflowInformationId = workflowInformationId;
		this.name = name;
		this.description = description;
		this.createrId = createrId;
		this.userId = userId;
		this.isShared = isShared;
		this.parentCaseId = parentCaseId;
		this.persistent = persistent;
		this.state = state;
		this.caseType = caseType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.processType = processType;
		this.processId = processId;
		this.processFileses = processFileses;
		this.downloadFileses = downloadFileses;
		this.uploadFileses = uploadFileses;
		this.processResultses = processResultses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getWorkflowInformationId() {
		return this.workflowInformationId;
	}

	public void setWorkflowInformationId(Integer workflowInformationId) {
		this.workflowInformationId = workflowInformationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCreaterId() {
		return this.createrId;
	}

	public void setCreaterId(Integer createrId) {
		this.createrId = createrId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Boolean getIsShared() {
		return this.isShared;
	}

	public void setIsShared(Boolean isShared) {
		this.isShared = isShared;
	}

	public Integer getParentCaseId() {
		return this.parentCaseId;
	}

	public void setParentCaseId(Integer parentCaseId) {
		this.parentCaseId = parentCaseId;
	}

	public Boolean getPersistent() {
		return this.persistent;
	}

	public void setPersistent(Boolean persistent) {
		this.persistent = persistent;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Integer getCaseType() {
		return this.caseType;
	}

	public void setCaseType(Integer caseType) {
		this.caseType = caseType;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getProcessType() {
		return this.processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Set getProcessFileses() {
		return this.processFileses;
	}

	public void setProcessFileses(Set processFileses) {
		this.processFileses = processFileses;
	}

	public Set getDownloadFileses() {
		return this.downloadFileses;
	}

	public void setDownloadFileses(Set downloadFileses) {
		this.downloadFileses = downloadFileses;
	}

	public Set getUploadFileses() {
		return this.uploadFileses;
	}

	public void setUploadFileses(Set uploadFileses) {
		this.uploadFileses = uploadFileses;
	}

	public Set getProcessResultses() {
		return this.processResultses;
	}

	public void setProcessResultses(Set processResultses) {
		this.processResultses = processResultses;
	}

}
