package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processflowobjects generated by hbm2java
 */
public class Processflowobjects implements java.io.Serializable {

	private Integer id;
	private int droolsRuleId;
	private String processId;
	private int flowId;
	private int fromActivityId;
	private int toActivityId;
	private String xslto2m;
	private String xsltm2i;
	private Integer oxmlid;
	private Integer mxmlid;
	private Integer ixmlid;

	public Processflowobjects() {
	}

	public Processflowobjects(int droolsRuleId, String processId, int flowId, int fromActivityId, int toActivityId) {
		this.droolsRuleId = droolsRuleId;
		this.processId = processId;
		this.flowId = flowId;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
	}

	public Processflowobjects(int droolsRuleId, String processId, int flowId, int fromActivityId, int toActivityId,
			String xslto2m, String xsltm2i, Integer oxmlid, Integer mxmlid, Integer ixmlid) {
		this.droolsRuleId = droolsRuleId;
		this.processId = processId;
		this.flowId = flowId;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
		this.xslto2m = xslto2m;
		this.xsltm2i = xsltm2i;
		this.oxmlid = oxmlid;
		this.mxmlid = mxmlid;
		this.ixmlid = ixmlid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getDroolsRuleId() {
		return this.droolsRuleId;
	}

	public void setDroolsRuleId(int droolsRuleId) {
		this.droolsRuleId = droolsRuleId;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	public int getFromActivityId() {
		return this.fromActivityId;
	}

	public void setFromActivityId(int fromActivityId) {
		this.fromActivityId = fromActivityId;
	}

	public int getToActivityId() {
		return this.toActivityId;
	}

	public void setToActivityId(int toActivityId) {
		this.toActivityId = toActivityId;
	}

	public String getXslto2m() {
		return this.xslto2m;
	}

	public void setXslto2m(String xslto2m) {
		this.xslto2m = xslto2m;
	}

	public String getXsltm2i() {
		return this.xsltm2i;
	}

	public void setXsltm2i(String xsltm2i) {
		this.xsltm2i = xsltm2i;
	}

	public Integer getOxmlid() {
		return this.oxmlid;
	}

	public void setOxmlid(Integer oxmlid) {
		this.oxmlid = oxmlid;
	}

	public Integer getMxmlid() {
		return this.mxmlid;
	}

	public void setMxmlid(Integer mxmlid) {
		this.mxmlid = mxmlid;
	}

	public Integer getIxmlid() {
		return this.ixmlid;
	}

	public void setIxmlid(Integer ixmlid) {
		this.ixmlid = ixmlid;
	}

}
