package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processlogs generated by hbm2java
 */
public class Processlogs implements java.io.Serializable {

	private Integer id;
	private String processId;
	private String log;
	private Long starttime;
	private Long endtime;
	private Long idletime;

	public Processlogs() {
	}

	public Processlogs(String processId) {
		this.processId = processId;
	}

	public Processlogs(String processId, String log, Long starttime, Long endtime, Long idletime) {
		this.processId = processId;
		this.log = log;
		this.starttime = starttime;
		this.endtime = endtime;
		this.idletime = idletime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public String getLog() {
		return this.log;
	}

	public void setLog(String log) {
		this.log = log;
	}

	public Long getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Long starttime) {
		this.starttime = starttime;
	}

	public Long getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Long endtime) {
		this.endtime = endtime;
	}

	public Long getIdletime() {
		return this.idletime;
	}

	public void setIdletime(Long idletime) {
		this.idletime = idletime;
	}

}
