package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processactivityinputmapping generated by hbm2java
 */
public class Processactivityinputmapping implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int activityId;
	private int dataflowId;
	private String inputSchema;
	private String inputXml;
	private String xslt;

	public Processactivityinputmapping() {
	}

	public Processactivityinputmapping(String processId, int activityId, int dataflowId) {
		this.processId = processId;
		this.activityId = activityId;
		this.dataflowId = dataflowId;
	}

	public Processactivityinputmapping(String processId, int activityId, int dataflowId, String inputSchema,
			String inputXml, String xslt) {
		this.processId = processId;
		this.activityId = activityId;
		this.dataflowId = dataflowId;
		this.inputSchema = inputSchema;
		this.inputXml = inputXml;
		this.xslt = xslt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public int getDataflowId() {
		return this.dataflowId;
	}

	public void setDataflowId(int dataflowId) {
		this.dataflowId = dataflowId;
	}

	public String getInputSchema() {
		return this.inputSchema;
	}

	public void setInputSchema(String inputSchema) {
		this.inputSchema = inputSchema;
	}

	public String getInputXml() {
		return this.inputXml;
	}

	public void setInputXml(String inputXml) {
		this.inputXml = inputXml;
	}

	public String getXslt() {
		return this.xslt;
	}

	public void setXslt(String xslt) {
		this.xslt = xslt;
	}

}
