package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Processevent generated by hbm2java
 */
@Entity
@Table(name = "processevent", catalog = "isdsp_dev")
public class Processevent implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int eventId;
	private String eventRepresentation;
	private String expressionforParse;
	private Short eventType;
	private Short logicType;
	private Integer activityId;
	private Short repeatedTime;
	private Date activeTime;
	private String eventName;
	private String description;

	public Processevent() {
	}

	public Processevent(String processId, int eventId) {
		this.processId = processId;
		this.eventId = eventId;
	}

	public Processevent(String processId, int eventId, String eventRepresentation, String expressionforParse,
			Short eventType, Short logicType, Integer activityId, Short repeatedTime, Date activeTime, String eventName,
			String description) {
		this.processId = processId;
		this.eventId = eventId;
		this.eventRepresentation = eventRepresentation;
		this.expressionforParse = expressionforParse;
		this.eventType = eventType;
		this.logicType = logicType;
		this.activityId = activityId;
		this.repeatedTime = repeatedTime;
		this.activeTime = activeTime;
		this.eventName = eventName;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "EventID", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "EventRepresentation")
	public String getEventRepresentation() {
		return this.eventRepresentation;
	}

	public void setEventRepresentation(String eventRepresentation) {
		this.eventRepresentation = eventRepresentation;
	}

	@Column(name = "ExpressionforParse")
	public String getExpressionforParse() {
		return this.expressionforParse;
	}

	public void setExpressionforParse(String expressionforParse) {
		this.expressionforParse = expressionforParse;
	}

	@Column(name = "EventType")
	public Short getEventType() {
		return this.eventType;
	}

	public void setEventType(Short eventType) {
		this.eventType = eventType;
	}

	@Column(name = "LogicType")
	public Short getLogicType() {
		return this.logicType;
	}

	public void setLogicType(Short logicType) {
		this.logicType = logicType;
	}

	@Column(name = "ActivityID")
	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	@Column(name = "RepeatedTime")
	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActiveTime", length = 19)
	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

	@Column(name = "EventName", length = 20)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "Description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
