package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Processprocessecarule generated by hbm2java
 */
public class Processprocessecarule implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int ruleId;
	private int eventId;
	private int conditionId;
	private String actionExpression;
	private Float probability;
	private Float probabilityCoefficient;
	private Date activeTime;
	private Short repeatedTime;

	public Processprocessecarule() {
	}

	public Processprocessecarule(String processId, int ruleId, int eventId, int conditionId) {
		this.processId = processId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
	}

	public Processprocessecarule(String processId, int ruleId, int eventId, int conditionId, String actionExpression,
			Float probability, Float probabilityCoefficient, Date activeTime, Short repeatedTime) {
		this.processId = processId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
		this.actionExpression = actionExpression;
		this.probability = probability;
		this.probabilityCoefficient = probabilityCoefficient;
		this.activeTime = activeTime;
		this.repeatedTime = repeatedTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(int conditionId) {
		this.conditionId = conditionId;
	}

	public String getActionExpression() {
		return this.actionExpression;
	}

	public void setActionExpression(String actionExpression) {
		this.actionExpression = actionExpression;
	}

	public Float getProbability() {
		return this.probability;
	}

	public void setProbability(Float probability) {
		this.probability = probability;
	}

	public Float getProbabilityCoefficient() {
		return this.probabilityCoefficient;
	}

	public void setProbabilityCoefficient(Float probabilityCoefficient) {
		this.probabilityCoefficient = probabilityCoefficient;
	}

	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

}
