package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Processactivityinvokingapplication generated by hbm2java
 */
public class Processactivityinvokingapplication implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int activityId;
	private int applicationId;
	private Short invocationType;
	private Integer inputXmlid;
	private Integer outputXmlid;
	private Date actualStartDate;
	private Date actualEndDate;
	private String result;

	public Processactivityinvokingapplication() {
	}

	public Processactivityinvokingapplication(String processId, int activityId, int applicationId) {
		this.processId = processId;
		this.activityId = activityId;
		this.applicationId = applicationId;
	}

	public Processactivityinvokingapplication(String processId, int activityId, int applicationId, Short invocationType,
			Integer inputXmlid, Integer outputXmlid, Date actualStartDate, Date actualEndDate, String result) {
		this.processId = processId;
		this.activityId = activityId;
		this.applicationId = applicationId;
		this.invocationType = invocationType;
		this.inputXmlid = inputXmlid;
		this.outputXmlid = outputXmlid;
		this.actualStartDate = actualStartDate;
		this.actualEndDate = actualEndDate;
		this.result = result;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public Short getInvocationType() {
		return this.invocationType;
	}

	public void setInvocationType(Short invocationType) {
		this.invocationType = invocationType;
	}

	public Integer getInputXmlid() {
		return this.inputXmlid;
	}

	public void setInputXmlid(Integer inputXmlid) {
		this.inputXmlid = inputXmlid;
	}

	public Integer getOutputXmlid() {
		return this.outputXmlid;
	}

	public void setOutputXmlid(Integer outputXmlid) {
		this.outputXmlid = outputXmlid;
	}

	public Date getActualStartDate() {
		return this.actualStartDate;
	}

	public void setActualStartDate(Date actualStartDate) {
		this.actualStartDate = actualStartDate;
	}

	public Date getActualEndDate() {
		return this.actualEndDate;
	}

	public void setActualEndDate(Date actualEndDate) {
		this.actualEndDate = actualEndDate;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
