package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processinherentvariable generated by hbm2java
 */
public class Processinherentvariable implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int objectId;
	private String objectName;
	private String description;
	private Short valueType;
	private String initialValue;
	private String value;

	public Processinherentvariable() {
	}

	public Processinherentvariable(String processId, int objectId) {
		this.processId = processId;
		this.objectId = objectId;
	}

	public Processinherentvariable(String processId, int objectId, String objectName, String description,
			Short valueType, String initialValue, String value) {
		this.processId = processId;
		this.objectId = objectId;
		this.objectName = objectName;
		this.description = description;
		this.valueType = valueType;
		this.initialValue = initialValue;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Short getValueType() {
		return this.valueType;
	}

	public void setValueType(Short valueType) {
		this.valueType = valueType;
	}

	public String getInitialValue() {
		return this.initialValue;
	}

	public void setInitialValue(String initialValue) {
		this.initialValue = initialValue;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
