package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Processevent generated by hbm2java
 */
public class Processevent implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int eventId;
	private String eventRepresentation;
	private String expressionforParse;
	private Short eventType;
	private Short logicType;
	private Integer activityId;
	private Short repeatedTime;
	private Date activeTime;
	private String eventName;
	private String description;

	public Processevent() {
	}

	public Processevent(String processId, int eventId) {
		this.processId = processId;
		this.eventId = eventId;
	}

	public Processevent(String processId, int eventId, String eventRepresentation, String expressionforParse,
			Short eventType, Short logicType, Integer activityId, Short repeatedTime, Date activeTime, String eventName,
			String description) {
		this.processId = processId;
		this.eventId = eventId;
		this.eventRepresentation = eventRepresentation;
		this.expressionforParse = expressionforParse;
		this.eventType = eventType;
		this.logicType = logicType;
		this.activityId = activityId;
		this.repeatedTime = repeatedTime;
		this.activeTime = activeTime;
		this.eventName = eventName;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public String getEventRepresentation() {
		return this.eventRepresentation;
	}

	public void setEventRepresentation(String eventRepresentation) {
		this.eventRepresentation = eventRepresentation;
	}

	public String getExpressionforParse() {
		return this.expressionforParse;
	}

	public void setExpressionforParse(String expressionforParse) {
		this.expressionforParse = expressionforParse;
	}

	public Short getEventType() {
		return this.eventType;
	}

	public void setEventType(Short eventType) {
		this.eventType = eventType;
	}

	public Short getLogicType() {
		return this.logicType;
	}

	public void setLogicType(Short logicType) {
		this.logicType = logicType;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
