package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processflow generated by hbm2java
 */
public class Processflow implements java.io.Serializable {

	private Integer id;
	private short modelType;
	private String processId;
	private int flowId;
	private Integer parentId;
	private short type;
	private short fromObjectType;
	private int objectId1;
	private short toObjectType;
	private int objectId2;

	public Processflow() {
	}

	public Processflow(short modelType, String processId, int flowId, short type, short fromObjectType, int objectId1,
			short toObjectType, int objectId2) {
		this.modelType = modelType;
		this.processId = processId;
		this.flowId = flowId;
		this.type = type;
		this.fromObjectType = fromObjectType;
		this.objectId1 = objectId1;
		this.toObjectType = toObjectType;
		this.objectId2 = objectId2;
	}

	public Processflow(short modelType, String processId, int flowId, Integer parentId, short type,
			short fromObjectType, int objectId1, short toObjectType, int objectId2) {
		this.modelType = modelType;
		this.processId = processId;
		this.flowId = flowId;
		this.parentId = parentId;
		this.type = type;
		this.fromObjectType = fromObjectType;
		this.objectId1 = objectId1;
		this.toObjectType = toObjectType;
		this.objectId2 = objectId2;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public short getModelType() {
		return this.modelType;
	}

	public void setModelType(short modelType) {
		this.modelType = modelType;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public short getFromObjectType() {
		return this.fromObjectType;
	}

	public void setFromObjectType(short fromObjectType) {
		this.fromObjectType = fromObjectType;
	}

	public int getObjectId1() {
		return this.objectId1;
	}

	public void setObjectId1(int objectId1) {
		this.objectId1 = objectId1;
	}

	public short getToObjectType() {
		return this.toObjectType;
	}

	public void setToObjectType(short toObjectType) {
		this.toObjectType = toObjectType;
	}

	public int getObjectId2() {
		return this.objectId2;
	}

	public void setObjectId2(int objectId2) {
		this.objectId2 = objectId2;
	}

}
