package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Processobject generated by hbm2java
 */
@Entity
@Table(name = "processobject", catalog = "isdsp_dev")
public class Processobject implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int objectId;
	private String objectName;
	private Boolean isinput;
	private Boolean isoutput;
	private Boolean isvisible;
	private Short objectType;
	private Short scope;
	private Short packageObjectId;
	private Short state;

	public Processobject() {
	}

	public Processobject(String processId, int objectId) {
		this.processId = processId;
		this.objectId = objectId;
	}

	public Processobject(String processId, int objectId, String objectName, Boolean isinput, Boolean isoutput,
			Boolean isvisible, Short objectType, Short scope, Short packageObjectId, Short state) {
		this.processId = processId;
		this.objectId = objectId;
		this.objectName = objectName;
		this.isinput = isinput;
		this.isoutput = isoutput;
		this.isvisible = isvisible;
		this.objectType = objectType;
		this.scope = scope;
		this.packageObjectId = packageObjectId;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "ObjectID", nullable = false)
	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	@Column(name = "ObjectName", length = 50)
	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	@Column(name = "ISInput")
	public Boolean getIsinput() {
		return this.isinput;
	}

	public void setIsinput(Boolean isinput) {
		this.isinput = isinput;
	}

	@Column(name = "ISOutput")
	public Boolean getIsoutput() {
		return this.isoutput;
	}

	public void setIsoutput(Boolean isoutput) {
		this.isoutput = isoutput;
	}

	@Column(name = "ISVisible")
	public Boolean getIsvisible() {
		return this.isvisible;
	}

	public void setIsvisible(Boolean isvisible) {
		this.isvisible = isvisible;
	}

	@Column(name = "ObjectType")
	public Short getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Short objectType) {
		this.objectType = objectType;
	}

	@Column(name = "Scope")
	public Short getScope() {
		return this.scope;
	}

	public void setScope(Short scope) {
		this.scope = scope;
	}

	@Column(name = "PackageObjectID")
	public Short getPackageObjectId() {
		return this.packageObjectId;
	}

	public void setPackageObjectId(Short packageObjectId) {
		this.packageObjectId = packageObjectId;
	}

	@Column(name = "State")
	public Short getState() {
		return this.state;
	}

	public void setState(Short state) {
		this.state = state;
	}

}
