package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Processflowobjectcontrol generated by hbm2java
 */
@Entity
@Table(name = "processflowobjectcontrol", catalog = "isdsp_dev")
public class Processflowobjectcontrol implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int flowId;
	private int objectId;
	private Short privilege;
	private Short repeatedTime;
	private Date activeTime;
	private String state;

	public Processflowobjectcontrol() {
	}

	public Processflowobjectcontrol(String processId, int flowId, int objectId) {
		this.processId = processId;
		this.flowId = flowId;
		this.objectId = objectId;
	}

	public Processflowobjectcontrol(String processId, int flowId, int objectId, Short privilege, Short repeatedTime,
			Date activeTime, String state) {
		this.processId = processId;
		this.flowId = flowId;
		this.objectId = objectId;
		this.privilege = privilege;
		this.repeatedTime = repeatedTime;
		this.activeTime = activeTime;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "FlowID", nullable = false)
	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	@Column(name = "ObjectID", nullable = false)
	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	@Column(name = "Privilege")
	public Short getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Short privilege) {
		this.privilege = privilege;
	}

	@Column(name = "RepeatedTime")
	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActiveTime", length = 19)
	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

	@Column(name = "State", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
