package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Processactivityinvokingapplication generated by hbm2java
 */
@Entity
@Table(name = "processactivityinvokingapplication", catalog = "isdsp_dev")
public class Processactivityinvokingapplication implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int activityId;
	private int applicationId;
	private Short invocationType;
	private Integer inputXmlid;
	private Integer outputXmlid;
	private Date actualStartDate;
	private Date actualEndDate;
	private String result;

	public Processactivityinvokingapplication() {
	}

	public Processactivityinvokingapplication(String processId, int activityId, int applicationId) {
		this.processId = processId;
		this.activityId = activityId;
		this.applicationId = applicationId;
	}

	public Processactivityinvokingapplication(String processId, int activityId, int applicationId, Short invocationType,
			Integer inputXmlid, Integer outputXmlid, Date actualStartDate, Date actualEndDate, String result) {
		this.processId = processId;
		this.activityId = activityId;
		this.applicationId = applicationId;
		this.invocationType = invocationType;
		this.inputXmlid = inputXmlid;
		this.outputXmlid = outputXmlid;
		this.actualStartDate = actualStartDate;
		this.actualEndDate = actualEndDate;
		this.result = result;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "ActivityID", nullable = false)
	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	@Column(name = "ApplicationID", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "InvocationType")
	public Short getInvocationType() {
		return this.invocationType;
	}

	public void setInvocationType(Short invocationType) {
		this.invocationType = invocationType;
	}

	@Column(name = "InputXMLID")
	public Integer getInputXmlid() {
		return this.inputXmlid;
	}

	public void setInputXmlid(Integer inputXmlid) {
		this.inputXmlid = inputXmlid;
	}

	@Column(name = "OutputXMLID")
	public Integer getOutputXmlid() {
		return this.outputXmlid;
	}

	public void setOutputXmlid(Integer outputXmlid) {
		this.outputXmlid = outputXmlid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActualStartDate", length = 19)
	public Date getActualStartDate() {
		return this.actualStartDate;
	}

	public void setActualStartDate(Date actualStartDate) {
		this.actualStartDate = actualStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActualEndDate", length = 19)
	public Date getActualEndDate() {
		return this.actualEndDate;
	}

	public void setActualEndDate(Date actualEndDate) {
		this.actualEndDate = actualEndDate;
	}

	@Column(name = "Result", length = 1)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
