package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processcondition generated by hbm2java
 */
public class Processcondition implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int conditionId;
	private String conditionRepresentation;
	private String conditionName;

	public Processcondition() {
	}

	public Processcondition(String processId, int conditionId) {
		this.processId = processId;
		this.conditionId = conditionId;
	}

	public Processcondition(String processId, int conditionId, String conditionRepresentation, String conditionName) {
		this.processId = processId;
		this.conditionId = conditionId;
		this.conditionRepresentation = conditionRepresentation;
		this.conditionName = conditionName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(int conditionId) {
		this.conditionId = conditionId;
	}

	public String getConditionRepresentation() {
		return this.conditionRepresentation;
	}

	public void setConditionRepresentation(String conditionRepresentation) {
		this.conditionRepresentation = conditionRepresentation;
	}

	public String getConditionName() {
		return this.conditionName;
	}

	public void setConditionName(String conditionName) {
		this.conditionName = conditionName;
	}

}
