package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcessInformations generated by hbm2java
 */
@Entity
@Table(name = "process_informations", catalog = "isdsp_dev")
public class ProcessInformations implements java.io.Serializable {

	private Integer id;
	private Integer workflowInformationId;
	private String name;
	private String description;
	private Integer createrId;
	private Integer userId;
	private Boolean isShared;
	private Integer parentCaseId;
	private Boolean persistent;
	private String state;
	private Integer caseType;
	private Date createdAt;
	private Date updatedAt;
	private String processType;
	private Integer processId;
	private Set<DownloadFile> downloadFileses = new HashSet<DownloadFile>(0);
	private Set<ProcessResult> processResultses = new HashSet<ProcessResult>(0);
	private Set<ProcessFiles> processFileses = new HashSet<ProcessFiles>(0);
	private Set<UploadFiles> uploadFileses = new HashSet<UploadFiles>(0);
	private Set<ProcessFiles> processFileses_1 = new HashSet<ProcessFiles>(0);
	private Set<DownloadFile> downloadFileses_1 = new HashSet<DownloadFile>(0);
	private Set<UploadFiles> uploadFileses_1 = new HashSet<UploadFiles>(0);
	private Set<ProcessResult> processResultses_1 = new HashSet<ProcessResult>(0);

	public ProcessInformations() {
	}

	public ProcessInformations(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProcessInformations(Integer workflowInformationId, String name, String description, Integer createrId,
			Integer userId, Boolean isShared, Integer parentCaseId, Boolean persistent, String state, Integer caseType,
			Date createdAt, Date updatedAt, String processType, Integer processId, Set<DownloadFile> downloadFileses,
			Set<ProcessResult> processResultses, Set<ProcessFiles> processFileses, Set<UploadFiles> uploadFileses,
			Set<ProcessFiles> processFileses_1, Set<DownloadFile> downloadFileses_1, Set<UploadFiles> uploadFileses_1,
			Set<ProcessResult> processResultses_1) {
		this.workflowInformationId = workflowInformationId;
		this.name = name;
		this.description = description;
		this.createrId = createrId;
		this.userId = userId;
		this.isShared = isShared;
		this.parentCaseId = parentCaseId;
		this.persistent = persistent;
		this.state = state;
		this.caseType = caseType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.processType = processType;
		this.processId = processId;
		this.downloadFileses = downloadFileses;
		this.processResultses = processResultses;
		this.processFileses = processFileses;
		this.uploadFileses = uploadFileses;
		this.processFileses_1 = processFileses_1;
		this.downloadFileses_1 = downloadFileses_1;
		this.uploadFileses_1 = uploadFileses_1;
		this.processResultses_1 = processResultses_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "workflow_information_id")
	public Integer getWorkflowInformationId() {
		return this.workflowInformationId;
	}

	public void setWorkflowInformationId(Integer workflowInformationId) {
		this.workflowInformationId = workflowInformationId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "creater_id")
	public Integer getCreaterId() {
		return this.createrId;
	}

	public void setCreaterId(Integer createrId) {
		this.createrId = createrId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "is_shared")
	public Boolean getIsShared() {
		return this.isShared;
	}

	public void setIsShared(Boolean isShared) {
		this.isShared = isShared;
	}

	@Column(name = "parent_case_id")
	public Integer getParentCaseId() {
		return this.parentCaseId;
	}

	public void setParentCaseId(Integer parentCaseId) {
		this.parentCaseId = parentCaseId;
	}

	@Column(name = "persistent")
	public Boolean getPersistent() {
		return this.persistent;
	}

	public void setPersistent(Boolean persistent) {
		this.persistent = persistent;
	}

	@Column(name = "state", length = 65535)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "case_type")
	public Integer getCaseType() {
		return this.caseType;
	}

	public void setCaseType(Integer caseType) {
		this.caseType = caseType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "process_type")
	public String getProcessType() {
		return this.processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	@Column(name = "process_id")
	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<DownloadFile> getDownloadFileses() {
		return this.downloadFileses;
	}

	public void setDownloadFileses(Set<DownloadFile> downloadFileses) {
		this.downloadFileses = downloadFileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<ProcessResult> getProcessResultses() {
		return this.processResultses;
	}

	public void setProcessResultses(Set<ProcessResult> processResultses) {
		this.processResultses = processResultses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<ProcessFiles> getProcessFileses() {
		return this.processFileses;
	}

	public void setProcessFileses(Set<ProcessFiles> processFileses) {
		this.processFileses = processFileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<UploadFiles> getUploadFileses() {
		return this.uploadFileses;
	}

	public void setUploadFileses(Set<UploadFiles> uploadFileses) {
		this.uploadFileses = uploadFileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<ProcessFiles> getProcessFileses_1() {
		return this.processFileses_1;
	}

	public void setProcessFileses_1(Set<ProcessFiles> processFileses_1) {
		this.processFileses_1 = processFileses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<DownloadFile> getDownloadFileses_1() {
		return this.downloadFileses_1;
	}

	public void setDownloadFileses_1(Set<DownloadFile> downloadFileses_1) {
		this.downloadFileses_1 = downloadFileses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<UploadFiles> getUploadFileses_1() {
		return this.uploadFileses_1;
	}

	public void setUploadFileses_1(Set<UploadFiles> uploadFileses_1) {
		this.uploadFileses_1 = uploadFileses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processInformations")
	public Set<ProcessResult> getProcessResultses_1() {
		return this.processResultses_1;
	}

	public void setProcessResultses_1(Set<ProcessResult> processResultses_1) {
		this.processResultses_1 = processResultses_1;
	}

}
