package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Processflowobjectcontrol generated by hbm2java
 */
public class Processflowobjectcontrol implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int flowId;
	private int objectId;
	private Short privilege;
	private Short repeatedTime;
	private Date activeTime;
	private String state;

	public Processflowobjectcontrol() {
	}

	public Processflowobjectcontrol(String processId, int flowId, int objectId) {
		this.processId = processId;
		this.flowId = flowId;
		this.objectId = objectId;
	}

	public Processflowobjectcontrol(String processId, int flowId, int objectId, Short privilege, Short repeatedTime,
			Date activeTime, String state) {
		this.processId = processId;
		this.flowId = flowId;
		this.objectId = objectId;
		this.privilege = privilege;
		this.repeatedTime = repeatedTime;
		this.activeTime = activeTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	public Short getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Short privilege) {
		this.privilege = privilege;
	}

	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
