package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Processrepeatedinformation generated by hbm2java
 */
@Entity
@Table(name = "processrepeatedinformation", catalog = "isdsp_dev")
public class Processrepeatedinformation implements java.io.Serializable {

	private Integer id;
	private String processId;
	private Short repeatedType;
	private Integer repeatedId1;
	private Integer repeatedId2;
	private Short repeatedTime;
	private Date startTime;
	private Date endTime;
	private String parameter1;
	private String parameter2;
	private String parameter3;

	public Processrepeatedinformation() {
	}

	public Processrepeatedinformation(String processId, Short repeatedType, Integer repeatedId1, Integer repeatedId2,
			Short repeatedTime, Date startTime, Date endTime, String parameter1, String parameter2, String parameter3) {
		this.processId = processId;
		this.repeatedType = repeatedType;
		this.repeatedId1 = repeatedId1;
		this.repeatedId2 = repeatedId2;
		this.repeatedTime = repeatedTime;
		this.startTime = startTime;
		this.endTime = endTime;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "RepeatedType")
	public Short getRepeatedType() {
		return this.repeatedType;
	}

	public void setRepeatedType(Short repeatedType) {
		this.repeatedType = repeatedType;
	}

	@Column(name = "RepeatedID1")
	public Integer getRepeatedId1() {
		return this.repeatedId1;
	}

	public void setRepeatedId1(Integer repeatedId1) {
		this.repeatedId1 = repeatedId1;
	}

	@Column(name = "RepeatedID2")
	public Integer getRepeatedId2() {
		return this.repeatedId2;
	}

	public void setRepeatedId2(Integer repeatedId2) {
		this.repeatedId2 = repeatedId2;
	}

	@Column(name = "RepeatedTime")
	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartTime", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndTime", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "Parameter1", length = 50)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "Parameter2", length = 50)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "Parameter3", length = 50)
	public String getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(String parameter3) {
		this.parameter3 = parameter3;
	}

}
