package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processapplication generated by hbm2java
 */
public class Processapplication implements java.io.Serializable {

	private Integer id;
	private String processId;
	private short applicationId;
	private String description;

	public Processapplication() {
	}

	public Processapplication(String processId, short applicationId) {
		this.processId = processId;
		this.applicationId = applicationId;
	}

	public Processapplication(String processId, short applicationId, String description) {
		this.processId = processId;
		this.applicationId = applicationId;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public short getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(short applicationId) {
		this.applicationId = applicationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
