package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processinformation generated by hbm2java
 */
public class Processinformation implements java.io.Serializable {

	private Integer id;
	private String processId;
	private String processName;
	private Short source;
	private Short caseType;
	private String parentCaseId;
	private Short maximalLayer;
	private String description;
	private Boolean persistent;
	private String state;
	private String durationUnit;
	private Float costUnit;
	private Integer twcid;

	public Processinformation() {
	}

	public Processinformation(String processId) {
		this.processId = processId;
	}

	public Processinformation(String processId, String processName, Short source, Short caseType, String parentCaseId,
			Short maximalLayer, String description, Boolean persistent, String state, String durationUnit,
			Float costUnit, Integer twcid) {
		this.processId = processId;
		this.processName = processName;
		this.source = source;
		this.caseType = caseType;
		this.parentCaseId = parentCaseId;
		this.maximalLayer = maximalLayer;
		this.description = description;
		this.persistent = persistent;
		this.state = state;
		this.durationUnit = durationUnit;
		this.costUnit = costUnit;
		this.twcid = twcid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	public Short getSource() {
		return this.source;
	}

	public void setSource(Short source) {
		this.source = source;
	}

	public Short getCaseType() {
		return this.caseType;
	}

	public void setCaseType(Short caseType) {
		this.caseType = caseType;
	}

	public String getParentCaseId() {
		return this.parentCaseId;
	}

	public void setParentCaseId(String parentCaseId) {
		this.parentCaseId = parentCaseId;
	}

	public Short getMaximalLayer() {
		return this.maximalLayer;
	}

	public void setMaximalLayer(Short maximalLayer) {
		this.maximalLayer = maximalLayer;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getPersistent() {
		return this.persistent;
	}

	public void setPersistent(Boolean persistent) {
		this.persistent = persistent;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDurationUnit() {
		return this.durationUnit;
	}

	public void setDurationUnit(String durationUnit) {
		this.durationUnit = durationUnit;
	}

	public Float getCostUnit() {
		return this.costUnit;
	}

	public void setCostUnit(Float costUnit) {
		this.costUnit = costUnit;
	}

	public Integer getTwcid() {
		return this.twcid;
	}

	public void setTwcid(Integer twcid) {
		this.twcid = twcid;
	}

}
