package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * ProcessResults generated by hbm2java
 */
public class ProcessResults implements java.io.Serializable {

	private Integer id;
	private ProcessInformations processInformations;
	private String body;
	private Date createdAt;
	private Date updatedAt;

	public ProcessResults() {
	}

	public ProcessResults(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProcessResults(ProcessInformations processInformations, String body, Date createdAt, Date updatedAt) {
		this.processInformations = processInformations;
		this.body = body;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProcessInformations getProcessInformations() {
		return this.processInformations;
	}

	public void setProcessInformations(ProcessInformations processInformations) {
		this.processInformations = processInformations;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
