package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * ProcessFiles generated by hbm2java
 */
public class ProcessFiles implements java.io.Serializable {

	private Integer id;
	private ProcessInformations processInformations;
	private String name;
	private String path;
	private Integer node;
	private Date createdAt;
	private Date updatedAt;

	public ProcessFiles() {
	}

	public ProcessFiles(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProcessFiles(ProcessInformations processInformations, String name, String path, Integer node, Date createdAt,
			Date updatedAt) {
		this.processInformations = processInformations;
		this.name = name;
		this.path = path;
		this.node = node;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProcessInformations getProcessInformations() {
		return this.processInformations;
	}

	public void setProcessInformations(ProcessInformations processInformations) {
		this.processInformations = processInformations;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Integer getNode() {
		return this.node;
	}

	public void setNode(Integer node) {
		this.node = node;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
