package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Processactivityinformation generated by hbm2java
 */
public class Processactivityinformation implements java.io.Serializable {

	private Integer id;
	private String processId;
	private int activityId;
	private String activityName;
	private Short activityType;
	private Short activityImplementation;
	private Short layer;
	private Integer parentId;
	private String description;
	private Boolean choiceManager;
	private Float startTime;
	private Float duration;
	private Integer iconId;
	private String activityUrl;
	private Integer multiPersonMode;
	private Integer submitPersonNumber;
	private Short repeatedTime;
	private Integer twcid;
	private String state;
	private Boolean isCallback;

	public Processactivityinformation() {
	}

	public Processactivityinformation(String processId, int activityId) {
		this.processId = processId;
		this.activityId = activityId;
	}

	public Processactivityinformation(String processId, int activityId, String activityName, Short activityType,
			Short activityImplementation, Short layer, Integer parentId, String description, Boolean choiceManager,
			Float startTime, Float duration, Integer iconId, String activityUrl, Integer multiPersonMode,
			Integer submitPersonNumber, Short repeatedTime, Integer twcid, String state, Boolean isCallback) {
		this.processId = processId;
		this.activityId = activityId;
		this.activityName = activityName;
		this.activityType = activityType;
		this.activityImplementation = activityImplementation;
		this.layer = layer;
		this.parentId = parentId;
		this.description = description;
		this.choiceManager = choiceManager;
		this.startTime = startTime;
		this.duration = duration;
		this.iconId = iconId;
		this.activityUrl = activityUrl;
		this.multiPersonMode = multiPersonMode;
		this.submitPersonNumber = submitPersonNumber;
		this.repeatedTime = repeatedTime;
		this.twcid = twcid;
		this.state = state;
		this.isCallback = isCallback;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public Short getActivityType() {
		return this.activityType;
	}

	public void setActivityType(Short activityType) {
		this.activityType = activityType;
	}

	public Short getActivityImplementation() {
		return this.activityImplementation;
	}

	public void setActivityImplementation(Short activityImplementation) {
		this.activityImplementation = activityImplementation;
	}

	public Short getLayer() {
		return this.layer;
	}

	public void setLayer(Short layer) {
		this.layer = layer;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getChoiceManager() {
		return this.choiceManager;
	}

	public void setChoiceManager(Boolean choiceManager) {
		this.choiceManager = choiceManager;
	}

	public Float getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Float startTime) {
		this.startTime = startTime;
	}

	public Float getDuration() {
		return this.duration;
	}

	public void setDuration(Float duration) {
		this.duration = duration;
	}

	public Integer getIconId() {
		return this.iconId;
	}

	public void setIconId(Integer iconId) {
		this.iconId = iconId;
	}

	public String getActivityUrl() {
		return this.activityUrl;
	}

	public void setActivityUrl(String activityUrl) {
		this.activityUrl = activityUrl;
	}

	public Integer getMultiPersonMode() {
		return this.multiPersonMode;
	}

	public void setMultiPersonMode(Integer multiPersonMode) {
		this.multiPersonMode = multiPersonMode;
	}

	public Integer getSubmitPersonNumber() {
		return this.submitPersonNumber;
	}

	public void setSubmitPersonNumber(Integer submitPersonNumber) {
		this.submitPersonNumber = submitPersonNumber;
	}

	public Short getRepeatedTime() {
		return this.repeatedTime;
	}

	public void setRepeatedTime(Short repeatedTime) {
		this.repeatedTime = repeatedTime;
	}

	public Integer getTwcid() {
		return this.twcid;
	}

	public void setTwcid(Integer twcid) {
		this.twcid = twcid;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Boolean getIsCallback() {
		return this.isCallback;
	}

	public void setIsCallback(Boolean isCallback) {
		this.isCallback = isCallback;
	}

}
