package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Processinformation generated by hbm2java
 */
@Entity
@Table(name = "processinformation", catalog = "isdsp_dev")
public class Processinformation implements java.io.Serializable {

	private Integer id;
	private String processId;
	private String processName;
	private Short source;
	private Short caseType;
	private String parentCaseId;
	private Short maximalLayer;
	private String description;
	private Boolean persistent;
	private String state;
	private String durationUnit;
	private Float costUnit;
	private Integer twcid;

	public Processinformation() {
	}

	public Processinformation(String processId) {
		this.processId = processId;
	}

	public Processinformation(String processId, String processName, Short source, Short caseType, String parentCaseId,
			Short maximalLayer, String description, Boolean persistent, String state, String durationUnit,
			Float costUnit, Integer twcid) {
		this.processId = processId;
		this.processName = processName;
		this.source = source;
		this.caseType = caseType;
		this.parentCaseId = parentCaseId;
		this.maximalLayer = maximalLayer;
		this.description = description;
		this.persistent = persistent;
		this.state = state;
		this.durationUnit = durationUnit;
		this.costUnit = costUnit;
		this.twcid = twcid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProcessID", nullable = false, length = 50)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "ProcessName", length = 50)
	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	@Column(name = "Source")
	public Short getSource() {
		return this.source;
	}

	public void setSource(Short source) {
		this.source = source;
	}

	@Column(name = "CaseType")
	public Short getCaseType() {
		return this.caseType;
	}

	public void setCaseType(Short caseType) {
		this.caseType = caseType;
	}

	@Column(name = "ParentCaseID", length = 50)
	public String getParentCaseId() {
		return this.parentCaseId;
	}

	public void setParentCaseId(String parentCaseId) {
		this.parentCaseId = parentCaseId;
	}

	@Column(name = "MaximalLayer")
	public Short getMaximalLayer() {
		return this.maximalLayer;
	}

	public void setMaximalLayer(Short maximalLayer) {
		this.maximalLayer = maximalLayer;
	}

	@Column(name = "Description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Persistent")
	public Boolean getPersistent() {
		return this.persistent;
	}

	public void setPersistent(Boolean persistent) {
		this.persistent = persistent;
	}

	@Column(name = "State", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "DurationUnit", length = 1)
	public String getDurationUnit() {
		return this.durationUnit;
	}

	public void setDurationUnit(String durationUnit) {
		this.durationUnit = durationUnit;
	}

	@Column(name = "CostUnit", precision = 12, scale = 0)
	public Float getCostUnit() {
		return this.costUnit;
	}

	public void setCostUnit(Float costUnit) {
		this.costUnit = costUnit;
	}

	@Column(name = "TWCID")
	public Integer getTwcid() {
		return this.twcid;
	}

	public void setTwcid(Integer twcid) {
		this.twcid = twcid;
	}

}
