package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SchemaMigrations generated by hbm2java
 */
@Entity
@Table(name = "schema_migrations", catalog = "isdsp_dev", uniqueConstraints = @UniqueConstraint(columnNames = "version"))
public class SchemaMigrations implements java.io.Serializable {

	private String version;

	public SchemaMigrations() {
	}

	public SchemaMigrations(String version) {
		this.version = version;
	}

	@Id

	@Column(name = "version", unique = true, nullable = false)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

}
