package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * SchemaMigrations generated by hbm2java
 */
public class SchemaMigrations implements java.io.Serializable {

	private String version;

	public SchemaMigrations() {
	}

	public SchemaMigrations(String version) {
		this.version = version;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

}
