package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SharedProcessPrivileges generated by hbm2java
 */
@Entity
@Table(name = "shared_process_privileges", catalog = "isdsp_dev")
public class SharedProcessPrivilege implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Integer editDepartmentId;
	private Integer executeDepartmentId;
	private Integer deleteDepartmentId;
	private Boolean isSharedSampleInput;
	private Date createdAt;
	private Date updatedAt;

	public SharedProcessPrivilege() {
	}

	public SharedProcessPrivilege(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public SharedProcessPrivilege(Integer processId, Integer editDepartmentId, Integer executeDepartmentId,
			Integer deleteDepartmentId, Boolean isSharedSampleInput, Date createdAt, Date updatedAt) {
		this.processId = processId;
		this.editDepartmentId = editDepartmentId;
		this.executeDepartmentId = executeDepartmentId;
		this.deleteDepartmentId = deleteDepartmentId;
		this.isSharedSampleInput = isSharedSampleInput;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "process_id")
	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	@Column(name = "edit_department_id")
	public Integer getEditDepartmentId() {
		return this.editDepartmentId;
	}

	public void setEditDepartmentId(Integer editDepartmentId) {
		this.editDepartmentId = editDepartmentId;
	}

	@Column(name = "execute_department_id")
	public Integer getExecuteDepartmentId() {
		return this.executeDepartmentId;
	}

	public void setExecuteDepartmentId(Integer executeDepartmentId) {
		this.executeDepartmentId = executeDepartmentId;
	}

	@Column(name = "delete_department_id")
	public Integer getDeleteDepartmentId() {
		return this.deleteDepartmentId;
	}

	public void setDeleteDepartmentId(Integer deleteDepartmentId) {
		this.deleteDepartmentId = deleteDepartmentId;
	}

	@Column(name = "is_shared_sample_input")
	public Boolean getIsSharedSampleInput() {
		return this.isSharedSampleInput;
	}

	public void setIsSharedSampleInput(Boolean isSharedSampleInput) {
		this.isSharedSampleInput = isSharedSampleInput;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
