package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * SharedProcessPrivileges generated by hbm2java
 */
public class SharedProcessPrivileges implements java.io.Serializable {

	private Integer id;
	private Integer processId;
	private Integer editDepartmentId;
	private Integer executeDepartmentId;
	private Integer deleteDepartmentId;
	private Boolean isSharedSampleInput;
	private Date createdAt;
	private Date updatedAt;

	public SharedProcessPrivileges() {
	}

	public SharedProcessPrivileges(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public SharedProcessPrivileges(Integer processId, Integer editDepartmentId, Integer executeDepartmentId,
			Integer deleteDepartmentId, Boolean isSharedSampleInput, Date createdAt, Date updatedAt) {
		this.processId = processId;
		this.editDepartmentId = editDepartmentId;
		this.executeDepartmentId = executeDepartmentId;
		this.deleteDepartmentId = deleteDepartmentId;
		this.isSharedSampleInput = isSharedSampleInput;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Integer getEditDepartmentId() {
		return this.editDepartmentId;
	}

	public void setEditDepartmentId(Integer editDepartmentId) {
		this.editDepartmentId = editDepartmentId;
	}

	public Integer getExecuteDepartmentId() {
		return this.executeDepartmentId;
	}

	public void setExecuteDepartmentId(Integer executeDepartmentId) {
		this.executeDepartmentId = executeDepartmentId;
	}

	public Integer getDeleteDepartmentId() {
		return this.deleteDepartmentId;
	}

	public void setDeleteDepartmentId(Integer deleteDepartmentId) {
		this.deleteDepartmentId = deleteDepartmentId;
	}

	public Boolean getIsSharedSampleInput() {
		return this.isSharedSampleInput;
	}

	public void setIsSharedSampleInput(Boolean isSharedSampleInput) {
		this.isSharedSampleInput = isSharedSampleInput;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
