package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Systemapplicationinformation generated by hbm2java
 */
public class Systemapplicationinformation implements java.io.Serializable {

	private Integer id;
	private int applicationId;
	private String description;
	private String applicationName;
	private Short applicationType;
	private Integer inputSchemaId;
	private Integer outputSchemaId;

	public Systemapplicationinformation() {
	}

	public Systemapplicationinformation(int applicationId) {
		this.applicationId = applicationId;
	}

	public Systemapplicationinformation(int applicationId, String description, String applicationName,
			Short applicationType, Integer inputSchemaId, Integer outputSchemaId) {
		this.applicationId = applicationId;
		this.description = description;
		this.applicationName = applicationName;
		this.applicationType = applicationType;
		this.inputSchemaId = inputSchemaId;
		this.outputSchemaId = outputSchemaId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	public Short getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationType(Short applicationType) {
		this.applicationType = applicationType;
	}

	public Integer getInputSchemaId() {
		return this.inputSchemaId;
	}

	public void setInputSchemaId(Integer inputSchemaId) {
		this.inputSchemaId = inputSchemaId;
	}

	public Integer getOutputSchemaId() {
		return this.outputSchemaId;
	}

	public void setOutputSchemaId(Integer outputSchemaId) {
		this.outputSchemaId = outputSchemaId;
	}

}
