package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Systemschema generated by hbm2java
 */
@Entity
@Table(name = "systemschema", catalog = "isdsp_dev")
public class Systemschema implements java.io.Serializable {

	private Integer id;
	private int schemaId;
	private String schemaName;
	private String description;
	private String schemaText;
	private int schemaType;

	public Systemschema() {
	}

	public Systemschema(int schemaId, int schemaType) {
		this.schemaId = schemaId;
		this.schemaType = schemaType;
	}

	public Systemschema(int schemaId, String schemaName, String description, String schemaText, int schemaType) {
		this.schemaId = schemaId;
		this.schemaName = schemaName;
		this.description = description;
		this.schemaText = schemaText;
		this.schemaType = schemaType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SchemaID", nullable = false)
	public int getSchemaId() {
		return this.schemaId;
	}

	public void setSchemaId(int schemaId) {
		this.schemaId = schemaId;
	}

	@Column(name = "SchemaName", length = 100)
	public String getSchemaName() {
		return this.schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	@Column(name = "description", length = 16777215)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SchemaText", length = 16777215)
	public String getSchemaText() {
		return this.schemaText;
	}

	public void setSchemaText(String schemaText) {
		this.schemaText = schemaText;
	}

	@Column(name = "SchemaType", nullable = false)
	public int getSchemaType() {
		return this.schemaType;
	}

	public void setSchemaType(int schemaType) {
		this.schemaType = schemaType;
	}

}
