package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Systemschema generated by hbm2java
 */
public class Systemschema implements java.io.Serializable {

	private Integer id;
	private int schemaId;
	private String schemaName;
	private String description;
	private String schemaText;
	private int schemaType;

	public Systemschema() {
	}

	public Systemschema(int schemaId, int schemaType) {
		this.schemaId = schemaId;
		this.schemaType = schemaType;
	}

	public Systemschema(int schemaId, String schemaName, String description, String schemaText, int schemaType) {
		this.schemaId = schemaId;
		this.schemaName = schemaName;
		this.description = description;
		this.schemaText = schemaText;
		this.schemaType = schemaType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSchemaId() {
		return this.schemaId;
	}

	public void setSchemaId(int schemaId) {
		this.schemaId = schemaId;
	}

	public String getSchemaName() {
		return this.schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSchemaText() {
		return this.schemaText;
	}

	public void setSchemaText(String schemaText) {
		this.schemaText = schemaText;
	}

	public int getSchemaType() {
		return this.schemaType;
	}

	public void setSchemaType(int schemaType) {
		this.schemaType = schemaType;
	}

}
