package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TaskPerformances generated by hbm2java
 */
public class TaskPerformances implements java.io.Serializable {

	private Integer id;
	private WikiPages wikiPages;
	private String name;
	private String description;
	private Date createdAt;
	private Date updatedAt;

	public TaskPerformances() {
	}

	public TaskPerformances(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public TaskPerformances(WikiPages wikiPages, String name, String description, Date createdAt, Date updatedAt) {
		this.wikiPages = wikiPages;
		this.name = name;
		this.description = description;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WikiPages getWikiPages() {
		return this.wikiPages;
	}

	public void setWikiPages(WikiPages wikiPages) {
		this.wikiPages = wikiPages;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
