package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskCategoryAndWikis generated by hbm2java
 */
@Entity
@Table(name = "task_category_and_wikis", catalog = "isdsp_dev")
public class TaskCategoryAndWiki implements java.io.Serializable {

	private Integer id;
	private WikiCategory wikiCategory;
	private Date createdAt;
	private Date updatedAt;
	private Integer wikiPageId;

	public TaskCategoryAndWiki() {
	}

	public TaskCategoryAndWiki(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public TaskCategoryAndWiki(WikiCategory wikiCategory, Date createdAt, Date updatedAt, Integer wikiPageId) {
		this.wikiCategory = wikiCategory;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.wikiPageId = wikiPageId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_category_id")
	public WikiCategory getTaskCategories() {
		return this.wikiCategory;
	}

	public void setTaskCategories(WikiCategory wikiCategory) {
		this.wikiCategory = wikiCategory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "wiki_page_id")
	public Integer getWikiPageId() {
		return this.wikiPageId;
	}

	public void setWikiPageId(Integer wikiPageId) {
		this.wikiPageId = wikiPageId;
	}

}
