package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TaskCategoryAndWikis generated by hbm2java
 */
public class TaskCategoryAndWikis implements java.io.Serializable {

	private Integer id;
	private TaskCategories taskCategories;
	private Date createdAt;
	private Date updatedAt;
	private Integer wikiPageId;

	public TaskCategoryAndWikis() {
	}

	public TaskCategoryAndWikis(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public TaskCategoryAndWikis(TaskCategories taskCategories, Date createdAt, Date updatedAt, Integer wikiPageId) {
		this.taskCategories = taskCategories;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.wikiPageId = wikiPageId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TaskCategories getTaskCategories() {
		return this.taskCategories;
	}

	public void setTaskCategories(TaskCategories taskCategories) {
		this.taskCategories = taskCategories;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getWikiPageId() {
		return this.wikiPageId;
	}

	public void setWikiPageId(Integer wikiPageId) {
		this.wikiPageId = wikiPageId;
	}

}
