package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TaskCategories generated by hbm2java
 */
public class TaskCategories implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set taskCategoryAndWikises = new HashSet(0);

	public TaskCategories() {
	}

	public TaskCategories(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public TaskCategories(String name, Date createdAt, Date updatedAt, Set taskCategoryAndWikises) {
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.taskCategoryAndWikises = taskCategoryAndWikises;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getTaskCategoryAndWikises() {
		return this.taskCategoryAndWikises;
	}

	public void setTaskCategoryAndWikises(Set taskCategoryAndWikises) {
		this.taskCategoryAndWikises = taskCategoryAndWikises;
	}

}
