package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TestAlgorithms generated by hbm2java
 */
public class TestAlgorithms implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer param1;
	private String param2;
	private String param3;
	private Integer processInformationId;
	private Date createdAt;
	private Date updatedAt;

	public TestAlgorithms() {
	}

	public TestAlgorithms(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public TestAlgorithms(String name, Integer param1, String param2, String param3, Integer processInformationId,
			Date createdAt, Date updatedAt) {
		this.name = name;
		this.param1 = param1;
		this.param2 = param2;
		this.param3 = param3;
		this.processInformationId = processInformationId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getParam1() {
		return this.param1;
	}

	public void setParam1(Integer param1) {
		this.param1 = param1;
	}

	public String getParam2() {
		return this.param2;
	}

	public void setParam2(String param2) {
		this.param2 = param2;
	}

	public String getParam3() {
		return this.param3;
	}

	public void setParam3(String param3) {
		this.param3 = param3;
	}

	public Integer getProcessInformationId() {
		return this.processInformationId;
	}

	public void setProcessInformationId(Integer processInformationId) {
		this.processInformationId = processInformationId;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
