package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestAlgorithms generated by hbm2java
 */
@Entity
@Table(name = "test_algorithms", catalog = "isdsp_dev")
public class TestAlgorithm implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer param1;
	private String param2;
	private String param3;
	private Integer processInformationId;
	private Date createdAt;
	private Date updatedAt;

	public TestAlgorithm() {
	}

	public TestAlgorithm(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public TestAlgorithm(String name, Integer param1, String param2, String param3, Integer processInformationId,
			Date createdAt, Date updatedAt) {
		this.name = name;
		this.param1 = param1;
		this.param2 = param2;
		this.param3 = param3;
		this.processInformationId = processInformationId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "param1")
	public Integer getParam1() {
		return this.param1;
	}

	public void setParam1(Integer param1) {
		this.param1 = param1;
	}

	@Column(name = "param2")
	public String getParam2() {
		return this.param2;
	}

	public void setParam2(String param2) {
		this.param2 = param2;
	}

	@Column(name = "param3")
	public String getParam3() {
		return this.param3;
	}

	public void setParam3(String param3) {
		this.param3 = param3;
	}

	@Column(name = "process_information_id")
	public Integer getProcessInformationId() {
		return this.processInformationId;
	}

	public void setProcessInformationId(Integer processInformationId) {
		this.processInformationId = processInformationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
