package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;


/**
 * ProcessInformations generated by hbm2java
 */
@Entity
@Table(name = "test_process_informations", catalog = "isdsp_dev")
public class TestProcessInformation implements java.io.Serializable {

	private Integer id;


	// 一对一关系,如果这个process是被分享的就有这个字段
	private TestSharedProcessRecord testSharedProcessRecord;
	// 多对一关系,执行多次sharedProcessRecord得到多个
	private TestSharedProcessRecord parentTestSharedProcessRecord;

	private TestProcessStar testProcessStar;

	public TestProcessInformation() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	


	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_shared_process_record_id")
	public TestSharedProcessRecord getTestSharedProcessRecord() {
		return testSharedProcessRecord;
	}

	public void setTestSharedProcessRecord(TestSharedProcessRecord sharedProcessRecord) {
		this.testSharedProcessRecord = sharedProcessRecord;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_test_shared_process_record_id")
	public TestSharedProcessRecord getParentTestSharedProcessRecord() {
		return parentTestSharedProcessRecord;
	}

	public void setParentTestSharedProcessRecord(TestSharedProcessRecord parentSharedProcessRecord) {
		this.parentTestSharedProcessRecord = parentSharedProcessRecord;
	}


	@OneToOne(fetch = FetchType.LAZY, mappedBy = "testProcessInformation")
	public TestProcessStar getTestProcessStar() {
		return testProcessStar;
	}

	public void setTestProcessStar(TestProcessStar processStar) {
		this.testProcessStar = processStar;
	}

}
