package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UploadFiles generated by hbm2java
 */
@Entity
@Table(name = "upload_files", catalog = "isdsp_dev")
public class UploadFile implements java.io.Serializable {

	private Integer id;
	private ProcessInformation processInformation;
	private String name;
	private String abstractPath;
	private String relativePath;
	private Date createdAt;
	private Date updatedAt;

	public UploadFile() {
	}

	public UploadFile(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	

	public UploadFile(ProcessInformation processInformation, String name, String abstractPath, String relativePath,
			Date createdAt, Date updatedAt) {
		this.processInformation = processInformation;
		this.name = name;
		this.abstractPath = abstractPath;
		this.relativePath = relativePath;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}



	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	
	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "process_information_id")
	public ProcessInformation getProcessInformation() {
		return processInformation;
	}

	public void setProcessInformation(ProcessInformation processInformation) {
		this.processInformation = processInformation;
	}

	@Column(name = "abstract_path", length = 65535)
	public String getAbstractPath() {
		return abstractPath;
	}

	public void setAbstractPath(String abstractPath) {
		this.abstractPath = abstractPath;
	}

	@Column(name = "relative_path", length = 65535)
	public String getRelativePath() {
		return relativePath;
	}

	public void setRelativePath(String relativePath) {
		this.relativePath = relativePath;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
