package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.Email;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	@Email(message="Wrong email")
	private String email;
	private String encryptedPassword;
	private String userName;
	private String personName;
	private String gender;
	private Date birthday;
	private String phoneNumber;
	private String resetPasswordToken;
	private Date resetPasswordSentAt;
	private Date rememberCreatedAt;
	private int signInCount;
	private Date currentSignInAt;
	private Date lastSignInAt;
	private String currentSignInIp;
	private String lastSignInIp;
	private Date createdAt;
	private Date updatedAt;
	private String role;
	private Set userPictureses = new HashSet(0);

	public Users() {
	}

	public Users(String email, String encryptedPassword, String userName, int signInCount) {
		this.email = email;
		this.encryptedPassword = encryptedPassword;
		this.userName = userName;
		this.signInCount = signInCount;
	}

	public Users(String email, String encryptedPassword, String userName, String personName, String gender,
			Date birthday, String phoneNumber, String resetPasswordToken, Date resetPasswordSentAt,
			Date rememberCreatedAt, int signInCount, Date currentSignInAt, Date lastSignInAt, String currentSignInIp,
			String lastSignInIp, Date createdAt, Date updatedAt, String role, Set userPictureses) {
		this.email = email;
		this.encryptedPassword = encryptedPassword;
		this.userName = userName;
		this.personName = personName;
		this.gender = gender;
		this.birthday = birthday;
		this.phoneNumber = phoneNumber;
		this.resetPasswordToken = resetPasswordToken;
		this.resetPasswordSentAt = resetPasswordSentAt;
		this.rememberCreatedAt = rememberCreatedAt;
		this.signInCount = signInCount;
		this.currentSignInAt = currentSignInAt;
		this.lastSignInAt = lastSignInAt;
		this.currentSignInIp = currentSignInIp;
		this.lastSignInIp = lastSignInIp;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.role = role;
		this.userPictureses = userPictureses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	//@NotNull(message="Password can not be null")
	public String getEncryptedPassword() {
		return this.encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword) {
		this.encryptedPassword = encryptedPassword;
	}

	//@NotNull(message="Username can not be null")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getResetPasswordToken() {
		return this.resetPasswordToken;
	}

	public void setResetPasswordToken(String resetPasswordToken) {
		this.resetPasswordToken = resetPasswordToken;
	}

	public Date getResetPasswordSentAt() {
		return this.resetPasswordSentAt;
	}

	public void setResetPasswordSentAt(Date resetPasswordSentAt) {
		this.resetPasswordSentAt = resetPasswordSentAt;
	}

	public Date getRememberCreatedAt() {
		return this.rememberCreatedAt;
	}

	public void setRememberCreatedAt(Date rememberCreatedAt) {
		this.rememberCreatedAt = rememberCreatedAt;
	}

	public int getSignInCount() {
		return this.signInCount;
	}

	public void setSignInCount(int signInCount) {
		this.signInCount = signInCount;
	}

	public Date getCurrentSignInAt() {
		return this.currentSignInAt;
	}

	public void setCurrentSignInAt(Date currentSignInAt) {
		this.currentSignInAt = currentSignInAt;
	}

	public Date getLastSignInAt() {
		return this.lastSignInAt;
	}

	public void setLastSignInAt(Date lastSignInAt) {
		this.lastSignInAt = lastSignInAt;
	}

	public String getCurrentSignInIp() {
		return this.currentSignInIp;
	}

	public void setCurrentSignInIp(String currentSignInIp) {
		this.currentSignInIp = currentSignInIp;
	}

	public String getLastSignInIp() {
		return this.lastSignInIp;
	}

	public void setLastSignInIp(String lastSignInIp) {
		this.lastSignInIp = lastSignInIp;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getUserPictureses() {
		return this.userPictureses;
	}

	public void setUserPictureses(Set userPictureses) {
		this.userPictureses = userPictureses;
	}

}
