package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * WikiRelationships generated by hbm2java
 */
public class WikiReferences implements java.io.Serializable {

	private Integer id;
	private WikiPages wikiPages;
	private String content;
	private String url;
	private Date createdAt;
	private Date updatedAt;

	public WikiReferences() {
	}

	public WikiReferences(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public WikiReferences(Integer id, WikiPages wikiPages, String context, String url, Date createdAt, Date updatedAt) {
		this.id = id;
		this.wikiPages = wikiPages;
		this.content = context;
		this.url = url;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}
	public WikiReferences(String context, String url, Date createdAt, Date updatedAt) {
		this.content = context;
		this.url = url;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WikiPages getWikiPages() {
		return wikiPages;
	}

	public void setWikiPages(WikiPages wikiPages) {
		this.wikiPages = wikiPages;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	

}
