package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WikiPageVersions generated by hbm2java
 */
@Entity
@Table(name = "wiki_page_versions", catalog = "isdsp_dev")
public class WikiPageVersion implements java.io.Serializable {

	private Integer id;
	private int pageId;
	//private Integer updatorId;
	private User userByUpdatorId;
	private Integer number;
	private String comment;
	private String path;
	private String title;
	private String content;
	private Date updatedAt;

	public WikiPageVersion() {
	}

	public WikiPageVersion(int pageId) {
		this.pageId = pageId;
	}

	public WikiPageVersion(int pageId, User userByUpdatorId, Integer number, String comment, String path, String title,
			String content, Date updatedAt) {
		this.pageId = pageId;
		this.userByUpdatorId = userByUpdatorId;
		this.number = number;
		this.comment = comment;
		this.path = path;
		this.title = title;
		this.content = content;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "page_id", nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}



	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updator_id")
	public User getUserByUpdatorId() {
		return userByUpdatorId;
	}

	public void setUserByUpdatorId(User userByUpdatorId) {
		this.userByUpdatorId = userByUpdatorId;
	}

}
