package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WikiPages generated by hbm2java
 */
public class WikiPages implements java.io.Serializable {

	private Integer id;
	private Integer creatorId;
	private Integer updatorId;
	private String path;
	private String title;
	private String content;
	private Date createdAt;
	private Date updatedAt;
	private Set wikiAndWorkflowInformationses = new HashSet(0);
	private Set taskPerformanceses = new HashSet(0);
	private Set wikiRelationshipses = new HashSet(0);

	public WikiPages() {
	}

	public WikiPages(Integer creatorId, Integer updatorId, String path, String title, String content, Date createdAt,
			Date updatedAt, Set wikiAndWorkflowInformationses, Set taskPerformanceses, Set wikiRelationshipses) {
		this.creatorId = creatorId;
		this.updatorId = updatorId;
		this.path = path;
		this.title = title;
		this.content = content;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.wikiAndWorkflowInformationses = wikiAndWorkflowInformationses;
		this.taskPerformanceses = taskPerformanceses;
		this.wikiRelationshipses = wikiRelationshipses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	public Integer getUpdatorId() {
		return this.updatorId;
	}

	public void setUpdatorId(Integer updatorId) {
		this.updatorId = updatorId;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getWikiAndWorkflowInformationses() {
		return this.wikiAndWorkflowInformationses;
	}

	public void setWikiAndWorkflowInformationses(Set wikiAndWorkflowInformationses) {
		this.wikiAndWorkflowInformationses = wikiAndWorkflowInformationses;
	}

	public Set getTaskPerformanceses() {
		return this.taskPerformanceses;
	}

	public void setTaskPerformanceses(Set taskPerformanceses) {
		this.taskPerformanceses = taskPerformanceses;
	}

	public Set getWikiRelationshipses() {
		return this.wikiRelationshipses;
	}

	public void setWikiRelationshipses(Set wikiRelationshipses) {
		this.wikiRelationshipses = wikiRelationshipses;
	}

}
