package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * WikiAndWorkflowInformations generated by hbm2java
 */
public class WikiAndWorkflowInformations implements java.io.Serializable {

	private Integer id;
	private WikiPages wikiPages;
	private WorkflowInformations workflowInformations;
	private Date createdAt;
	private Date updatedAt;

	public WikiAndWorkflowInformations() {
	}

	public WikiAndWorkflowInformations(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public WikiAndWorkflowInformations(WikiPages wikiPages, WorkflowInformations workflowInformations, Date createdAt,
			Date updatedAt) {
		this.wikiPages = wikiPages;
		this.workflowInformations = workflowInformations;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WikiPages getWikiPages() {
		return this.wikiPages;
	}

	public void setWikiPages(WikiPages wikiPages) {
		this.wikiPages = wikiPages;
	}

	public WorkflowInformations getWorkflowInformations() {
		return this.workflowInformations;
	}

	public void setWorkflowInformations(WorkflowInformations workflowInformations) {
		this.workflowInformations = workflowInformations;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
