package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * WikiRelationships generated by hbm2java
 */
public class WikiRelationships implements java.io.Serializable {

	private Integer id;
	private WikiPages wikiPages;
	private Integer relatedWikiPageId;
	private Date createdAt;
	private Date updatedAt;

	public WikiRelationships() {
	}

	public WikiRelationships(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public WikiRelationships(WikiPages wikiPages, Integer relatedWikiPageId, Date createdAt, Date updatedAt) {
		this.wikiPages = wikiPages;
		this.relatedWikiPageId = relatedWikiPageId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WikiPages getWikiPages() {
		return this.wikiPages;
	}

	public void setWikiPages(WikiPages wikiPages) {
		this.wikiPages = wikiPages;
	}

	public Integer getRelatedWikiPageId() {
		return this.relatedWikiPageId;
	}

	public void setRelatedWikiPageId(Integer relatedWikiPageId) {
		this.relatedWikiPageId = relatedWikiPageId;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
