package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * WorkflowComments generated by hbm2java
 */
public class WorkflowComments implements java.io.Serializable {

	private Integer id;
	private String title;
	private String body;
	private Integer score;
	private Integer authorId;
	private Integer commentParentId;
	private Integer workflowInformationId;
	private Integer processId;
	private Date createdAt;
	private Date updatedAt;

	public WorkflowComments() {
	}

	public WorkflowComments(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public WorkflowComments(String title, String body, Integer score, Integer authorId, Integer commentParentId,
			Integer workflowInformationId, Integer processId, Date createdAt, Date updatedAt) {
		this.title = title;
		this.body = body;
		this.score = score;
		this.authorId = authorId;
		this.commentParentId = commentParentId;
		this.workflowInformationId = workflowInformationId;
		this.processId = processId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public Integer getCommentParentId() {
		return this.commentParentId;
	}

	public void setCommentParentId(Integer commentParentId) {
		this.commentParentId = commentParentId;
	}

	public Integer getWorkflowInformationId() {
		return this.workflowInformationId;
	}

	public void setWorkflowInformationId(Integer workflowInformationId) {
		this.workflowInformationId = workflowInformationId;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
