package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowapplication generated by hbm2java
 */
public class Workflowapplication implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private short applicationId;
	private String description;

	public Workflowapplication() {
	}

	public Workflowapplication(int workflowId, short applicationId) {
		this.workflowId = workflowId;
		this.applicationId = applicationId;
	}

	public Workflowapplication(int workflowId, short applicationId, String description) {
		this.workflowId = workflowId;
		this.applicationId = applicationId;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public short getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(short applicationId) {
		this.applicationId = applicationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
