package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Workflowapplication generated by hbm2java
 */
@Entity
@Table(name = "workflowapplication", catalog = "isdsp_dev")
public class Workflowapplication implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private short applicationId;
	private String description;

	public Workflowapplication() {
	}

	public Workflowapplication(int workflowId, short applicationId) {
		this.workflowId = workflowId;
		this.applicationId = applicationId;
	}

	public Workflowapplication(int workflowId, short applicationId, String description) {
		this.workflowId = workflowId;
		this.applicationId = applicationId;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "WorkflowID", nullable = false)
	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "ApplicationID", nullable = false)
	public short getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(short applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
