package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Workflowflowobjects generated by hbm2java
 */
@Entity
@Table(name = "workflowflowobjects", catalog = "isdsp_dev")
public class Workflowflowobjects implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int flowId;
	private Integer droolsRuleId;
	private Integer fromActivityId;
	private Integer toActivityId;
	private String xslto2m;
	private String xsltm2i;
	private Integer oxmlid;
	private Integer mxmlid;
	private Integer ixmlid;

	public Workflowflowobjects() {
	}

	public Workflowflowobjects(int workflowId, int flowId) {
		this.workflowId = workflowId;
		this.flowId = flowId;
	}

	public Workflowflowobjects(int workflowId, int flowId, Integer droolsRuleId, Integer fromActivityId,
			Integer toActivityId, String xslto2m, String xsltm2i, Integer oxmlid, Integer mxmlid, Integer ixmlid) {
		this.workflowId = workflowId;
		this.flowId = flowId;
		this.droolsRuleId = droolsRuleId;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
		this.xslto2m = xslto2m;
		this.xsltm2i = xsltm2i;
		this.oxmlid = oxmlid;
		this.mxmlid = mxmlid;
		this.ixmlid = ixmlid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "WorkflowID", nullable = false)
	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "FlowID", nullable = false)
	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	@Column(name = "DroolsRuleID")
	public Integer getDroolsRuleId() {
		return this.droolsRuleId;
	}

	public void setDroolsRuleId(Integer droolsRuleId) {
		this.droolsRuleId = droolsRuleId;
	}

	@Column(name = "FromActivityID")
	public Integer getFromActivityId() {
		return this.fromActivityId;
	}

	public void setFromActivityId(Integer fromActivityId) {
		this.fromActivityId = fromActivityId;
	}

	@Column(name = "ToActivityID")
	public Integer getToActivityId() {
		return this.toActivityId;
	}

	public void setToActivityId(Integer toActivityId) {
		this.toActivityId = toActivityId;
	}

	@Column(name = "XSLTO2M")
	public String getXslto2m() {
		return this.xslto2m;
	}

	public void setXslto2m(String xslto2m) {
		this.xslto2m = xslto2m;
	}

	@Column(name = "XSLTM2I")
	public String getXsltm2i() {
		return this.xsltm2i;
	}

	public void setXsltm2i(String xsltm2i) {
		this.xsltm2i = xsltm2i;
	}

	@Column(name = "OXMLID")
	public Integer getOxmlid() {
		return this.oxmlid;
	}

	public void setOxmlid(Integer oxmlid) {
		this.oxmlid = oxmlid;
	}

	@Column(name = "MXMLID")
	public Integer getMxmlid() {
		return this.mxmlid;
	}

	public void setMxmlid(Integer mxmlid) {
		this.mxmlid = mxmlid;
	}

	@Column(name = "IXMLID")
	public Integer getIxmlid() {
		return this.ixmlid;
	}

	public void setIxmlid(Integer ixmlid) {
		this.ixmlid = ixmlid;
	}

}
