package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowinherentvariable generated by hbm2java
 */
public class Workflowinherentvariable implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int objectId;
	private String objectName;
	private String description;
	private Short valueType;
	private String initialValue;

	public Workflowinherentvariable() {
	}

	public Workflowinherentvariable(int workflowId, int objectId) {
		this.workflowId = workflowId;
		this.objectId = objectId;
	}

	public Workflowinherentvariable(int workflowId, int objectId, String objectName, String description,
			Short valueType, String initialValue) {
		this.workflowId = workflowId;
		this.objectId = objectId;
		this.objectName = objectName;
		this.description = description;
		this.valueType = valueType;
		this.initialValue = initialValue;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Short getValueType() {
		return this.valueType;
	}

	public void setValueType(Short valueType) {
		this.valueType = valueType;
	}

	public String getInitialValue() {
		return this.initialValue;
	}

	public void setInitialValue(String initialValue) {
		this.initialValue = initialValue;
	}

}
