package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowflowobjects generated by hbm2java
 */
public class Workflowflowobjects implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int flowId;
	private Integer droolsRuleId;
	private Integer fromActivityId;
	private Integer toActivityId;
	private String xslto2m;
	private String xsltm2i;
	private Integer oxmlid;
	private Integer mxmlid;
	private Integer ixmlid;

	public Workflowflowobjects() {
	}

	public Workflowflowobjects(int workflowId, int flowId) {
		this.workflowId = workflowId;
		this.flowId = flowId;
	}

	public Workflowflowobjects(int workflowId, int flowId, Integer droolsRuleId, Integer fromActivityId,
			Integer toActivityId, String xslto2m, String xsltm2i, Integer oxmlid, Integer mxmlid, Integer ixmlid) {
		this.workflowId = workflowId;
		this.flowId = flowId;
		this.droolsRuleId = droolsRuleId;
		this.fromActivityId = fromActivityId;
		this.toActivityId = toActivityId;
		this.xslto2m = xslto2m;
		this.xsltm2i = xsltm2i;
		this.oxmlid = oxmlid;
		this.mxmlid = mxmlid;
		this.ixmlid = ixmlid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public int getFlowId() {
		return this.flowId;
	}

	public void setFlowId(int flowId) {
		this.flowId = flowId;
	}

	public Integer getDroolsRuleId() {
		return this.droolsRuleId;
	}

	public void setDroolsRuleId(Integer droolsRuleId) {
		this.droolsRuleId = droolsRuleId;
	}

	public Integer getFromActivityId() {
		return this.fromActivityId;
	}

	public void setFromActivityId(Integer fromActivityId) {
		this.fromActivityId = fromActivityId;
	}

	public Integer getToActivityId() {
		return this.toActivityId;
	}

	public void setToActivityId(Integer toActivityId) {
		this.toActivityId = toActivityId;
	}

	public String getXslto2m() {
		return this.xslto2m;
	}

	public void setXslto2m(String xslto2m) {
		this.xslto2m = xslto2m;
	}

	public String getXsltm2i() {
		return this.xsltm2i;
	}

	public void setXsltm2i(String xsltm2i) {
		this.xsltm2i = xsltm2i;
	}

	public Integer getOxmlid() {
		return this.oxmlid;
	}

	public void setOxmlid(Integer oxmlid) {
		this.oxmlid = oxmlid;
	}

	public Integer getMxmlid() {
		return this.mxmlid;
	}

	public void setMxmlid(Integer mxmlid) {
		this.mxmlid = mxmlid;
	}

	public Integer getIxmlid() {
		return this.ixmlid;
	}

	public void setIxmlid(Integer ixmlid) {
		this.ixmlid = ixmlid;
	}

}
