package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkflowInformations generated by hbm2java
 */
public class WorkflowInformations implements java.io.Serializable {

	private Integer id;
	private String name;
	private String introduction;
	private String detialDescription;
	private String versionName;
	private Integer categoryId;
	private Integer tagId;
	private Integer authorId;
	private Integer lastEditorId;
	private Integer status;
	private Date createtime;
	private Date validFrom;
	private Date validTo;
	private Boolean persistent;
	private Integer priority;
	private Integer mostPossibleDuration;
	private Integer minimalDuration;
	private Integer maximalDuration;
	private Date createdAt;
	private Date updatedAt;
	private String xml;
	private Set wikiAndWorkflowInformationses = new HashSet(0);
	private Set nodeInformationses = new HashSet(0);

	public WorkflowInformations() {
	}

	public WorkflowInformations(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public WorkflowInformations(String name, String introduction, String detialDescription, String versionName,
			Integer categoryId, Integer tagId, Integer authorId, Integer lastEditorId, Integer status, Date createtime,
			Date validFrom, Date validTo, Boolean persistent, Integer priority, Integer mostPossibleDuration,
			Integer minimalDuration, Integer maximalDuration, Date createdAt, Date updatedAt, String xml,
			Set wikiAndWorkflowInformationses, Set nodeInformationses) {
		this.name = name;
		this.introduction = introduction;
		this.detialDescription = detialDescription;
		this.versionName = versionName;
		this.categoryId = categoryId;
		this.tagId = tagId;
		this.authorId = authorId;
		this.lastEditorId = lastEditorId;
		this.status = status;
		this.createtime = createtime;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.persistent = persistent;
		this.priority = priority;
		this.mostPossibleDuration = mostPossibleDuration;
		this.minimalDuration = minimalDuration;
		this.maximalDuration = maximalDuration;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.xml = xml;
		this.wikiAndWorkflowInformationses = wikiAndWorkflowInformationses;
		this.nodeInformationses = nodeInformationses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getDetialDescription() {
		return this.detialDescription;
	}

	public void setDetialDescription(String detialDescription) {
		this.detialDescription = detialDescription;
	}

	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public Integer getLastEditorId() {
		return this.lastEditorId;
	}

	public void setLastEditorId(Integer lastEditorId) {
		this.lastEditorId = lastEditorId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public Boolean getPersistent() {
		return this.persistent;
	}

	public void setPersistent(Boolean persistent) {
		this.persistent = persistent;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getMostPossibleDuration() {
		return this.mostPossibleDuration;
	}

	public void setMostPossibleDuration(Integer mostPossibleDuration) {
		this.mostPossibleDuration = mostPossibleDuration;
	}

	public Integer getMinimalDuration() {
		return this.minimalDuration;
	}

	public void setMinimalDuration(Integer minimalDuration) {
		this.minimalDuration = minimalDuration;
	}

	public Integer getMaximalDuration() {
		return this.maximalDuration;
	}

	public void setMaximalDuration(Integer maximalDuration) {
		this.maximalDuration = maximalDuration;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getXml() {
		return this.xml;
	}

	public void setXml(String xml) {
		this.xml = xml;
	}

	public Set getWikiAndWorkflowInformationses() {
		return this.wikiAndWorkflowInformationses;
	}

	public void setWikiAndWorkflowInformationses(Set wikiAndWorkflowInformationses) {
		this.wikiAndWorkflowInformationses = wikiAndWorkflowInformationses;
	}

	public Set getNodeInformationses() {
		return this.nodeInformationses;
	}

	public void setNodeInformationses(Set nodeInformationses) {
		this.nodeInformationses = nodeInformationses;
	}

}
