package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowevent generated by hbm2java
 */
public class Workflowevent implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int eventId;
	private String eventName;
	private String description;
	private String eventRepresentation;
	private Short eventType;
	private Short logicType;
	private Integer activityId;

	public Workflowevent() {
	}

	public Workflowevent(int workflowId, int eventId) {
		this.workflowId = workflowId;
		this.eventId = eventId;
	}

	public Workflowevent(int workflowId, int eventId, String eventName, String description, String eventRepresentation,
			Short eventType, Short logicType, Integer activityId) {
		this.workflowId = workflowId;
		this.eventId = eventId;
		this.eventName = eventName;
		this.description = description;
		this.eventRepresentation = eventRepresentation;
		this.eventType = eventType;
		this.logicType = logicType;
		this.activityId = activityId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEventRepresentation() {
		return this.eventRepresentation;
	}

	public void setEventRepresentation(String eventRepresentation) {
		this.eventRepresentation = eventRepresentation;
	}

	public Short getEventType() {
		return this.eventType;
	}

	public void setEventType(Short eventType) {
		this.eventType = eventType;
	}

	public Short getLogicType() {
		return this.logicType;
	}

	public void setLogicType(Short logicType) {
		this.logicType = logicType;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

}
