package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkflowInformations generated by hbm2java
 */
@Entity
@Table(name = "workflow_informations", catalog = "isdsp_dev")
public class WorkflowInformation implements java.io.Serializable {

	private Integer id;
	private User author;
	private String name;
	private String introduction;
	private String detialDescription;
	private String versionName;
	private Integer categoryId;
	private Integer tagId;
	private Integer lastEditorId;
	private Integer status;
	private Date createtime;
	private Date validFrom;
	private Date validTo;
	private Boolean persistent;
	private Integer priority;
	private Integer mostPossibleDuration;
	private Integer minimalDuration;
	private Integer maximalDuration;
	private Date createdAt;
	private Date updatedAt;
	private String xml;
	private Set<WikiAndWorkflowInformation> wikiAndWorkflowInformations = new HashSet<WikiAndWorkflowInformation>(
			0);
	private Set<NodeInformation> nodeInformations = new HashSet<NodeInformation>(0);

	public WorkflowInformation() {
	}

	public WorkflowInformation(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public WorkflowInformation(User users, String name, String introduction, String detialDescription,
			String versionName, Integer categoryId, Integer tagId, Integer lastEditorId, Integer status,
			Date createtime, Date validFrom, Date validTo, Boolean persistent, Integer priority,
			Integer mostPossibleDuration, Integer minimalDuration, Integer maximalDuration, Date createdAt,
			Date updatedAt, String xml, Set<WikiAndWorkflowInformation> wikiAndWorkflowInformationses,
			Set<NodeInformation> nodeInformationses) {
		this.author = users;
		this.name = name;
		this.introduction = introduction;
		this.detialDescription = detialDescription;
		this.versionName = versionName;
		this.categoryId = categoryId;
		this.tagId = tagId;
		this.lastEditorId = lastEditorId;
		this.status = status;
		this.createtime = createtime;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.persistent = persistent;
		this.priority = priority;
		this.mostPossibleDuration = mostPossibleDuration;
		this.minimalDuration = minimalDuration;
		this.maximalDuration = maximalDuration;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.xml = xml;
		this.wikiAndWorkflowInformations = wikiAndWorkflowInformationses;
		this.nodeInformations = nodeInformationses;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id")
	public User getAuthor() {
		return this.author;
	}

	public void setAuthor(User users) {
		this.author = users;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "introduction", length = 65535)
	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	@Column(name = "detial_description", length = 65535)
	public String getDetialDescription() {
		return this.detialDescription;
	}

	public void setDetialDescription(String detialDescription) {
		this.detialDescription = detialDescription;
	}

	@Column(name = "version_name", length = 65535)
	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "tag_id")
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	@Column(name = "last_editor_id")
	public Integer getLastEditorId() {
		return this.lastEditorId;
	}

	public void setLastEditorId(Integer lastEditorId) {
		this.lastEditorId = lastEditorId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_from", length = 19)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_to", length = 19)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Column(name = "persistent")
	public Boolean getPersistent() {
		return this.persistent;
	}

	public void setPersistent(Boolean persistent) {
		this.persistent = persistent;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "most_possible_duration")
	public Integer getMostPossibleDuration() {
		return this.mostPossibleDuration;
	}

	public void setMostPossibleDuration(Integer mostPossibleDuration) {
		this.mostPossibleDuration = mostPossibleDuration;
	}

	@Column(name = "minimal_duration")
	public Integer getMinimalDuration() {
		return this.minimalDuration;
	}

	public void setMinimalDuration(Integer minimalDuration) {
		this.minimalDuration = minimalDuration;
	}

	@Column(name = "maximal_duration")
	public Integer getMaximalDuration() {
		return this.maximalDuration;
	}

	public void setMaximalDuration(Integer maximalDuration) {
		this.maximalDuration = maximalDuration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "xml", length = 65535)
	public String getXml() {
		return this.xml;
	}

	public void setXml(String xml) {
		this.xml = xml;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workflowInformations")
	public Set<WikiAndWorkflowInformation> getWikiAndWorkflowInformations() {
		return this.wikiAndWorkflowInformations;
	}

	public void setWikiAndWorkflowInformations(Set<WikiAndWorkflowInformation> wikiAndWorkflowInformationses) {
		this.wikiAndWorkflowInformations = wikiAndWorkflowInformationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workflowInformations")
	public Set<NodeInformation> getNodeInformations() {
		return this.nodeInformations;
	}

	public void setNodeInformations(Set<NodeInformation> nodeInformationses) {
		this.nodeInformations = nodeInformationses;
	}



}
