package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowobject generated by hbm2java
 */
public class Workflowobject implements java.io.Serializable {

	private Integer id;
	private String workflowId;
	private Integer objectId;
	private String objectName;
	private Boolean isinput;
	private Boolean isoutput;
	private Boolean isvisible;
	private Short objectType;
	private Short scope;
	private Short packageObjectId;

	public Workflowobject() {
	}

	public Workflowobject(String workflowId, Integer objectId, String objectName, Boolean isinput, Boolean isoutput,
			Boolean isvisible, Short objectType, Short scope, Short packageObjectId) {
		this.workflowId = workflowId;
		this.objectId = objectId;
		this.objectName = objectName;
		this.isinput = isinput;
		this.isoutput = isoutput;
		this.isvisible = isvisible;
		this.objectType = objectType;
		this.scope = scope;
		this.packageObjectId = packageObjectId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(String workflowId) {
		this.workflowId = workflowId;
	}

	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public Boolean getIsinput() {
		return this.isinput;
	}

	public void setIsinput(Boolean isinput) {
		this.isinput = isinput;
	}

	public Boolean getIsoutput() {
		return this.isoutput;
	}

	public void setIsoutput(Boolean isoutput) {
		this.isoutput = isoutput;
	}

	public Boolean getIsvisible() {
		return this.isvisible;
	}

	public void setIsvisible(Boolean isvisible) {
		this.isvisible = isvisible;
	}

	public Short getObjectType() {
		return this.objectType;
	}

	public void setObjectType(Short objectType) {
		this.objectType = objectType;
	}

	public Short getScope() {
		return this.scope;
	}

	public void setScope(Short scope) {
		this.scope = scope;
	}

	public Short getPackageObjectId() {
		return this.packageObjectId;
	}

	public void setPackageObjectId(Short packageObjectId) {
		this.packageObjectId = packageObjectId;
	}

}
