package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkflowInformationAndTags generated by hbm2java
 */
@Entity
@Table(name = "workflow_information_and_tags", catalog = "isdsp_dev")
public class WorkflowInformationAndTag implements java.io.Serializable {

	private Integer id;
	private Integer workflowInformationId;
	private Integer workflowTagId;
	private Date createdAt;
	private Date updatedAt;

	public WorkflowInformationAndTag() {
	}

	public WorkflowInformationAndTag(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public WorkflowInformationAndTag(Integer workflowInformationId, Integer workflowTagId, Date createdAt,
			Date updatedAt) {
		this.workflowInformationId = workflowInformationId;
		this.workflowTagId = workflowTagId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "workflow_information_id")
	public Integer getWorkflowInformationId() {
		return this.workflowInformationId;
	}

	public void setWorkflowInformationId(Integer workflowInformationId) {
		this.workflowInformationId = workflowInformationId;
	}

	@Column(name = "workflow_tag_id")
	public Integer getWorkflowTagId() {
		return this.workflowTagId;
	}

	public void setWorkflowTagId(Integer workflowTagId) {
		this.workflowTagId = workflowTagId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
