package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowcondition generated by hbm2java
 */
public class Workflowcondition implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int conditionId;
	private String conditionRepresentation;
	private String conditionName;

	public Workflowcondition() {
	}

	public Workflowcondition(int workflowId, int conditionId) {
		this.workflowId = workflowId;
		this.conditionId = conditionId;
	}

	public Workflowcondition(int workflowId, int conditionId, String conditionRepresentation, String conditionName) {
		this.workflowId = workflowId;
		this.conditionId = conditionId;
		this.conditionRepresentation = conditionRepresentation;
		this.conditionName = conditionName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public int getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(int conditionId) {
		this.conditionId = conditionId;
	}

	public String getConditionRepresentation() {
		return this.conditionRepresentation;
	}

	public void setConditionRepresentation(String conditionRepresentation) {
		this.conditionRepresentation = conditionRepresentation;
	}

	public String getConditionName() {
		return this.conditionName;
	}

	public void setConditionName(String conditionName) {
		this.conditionName = conditionName;
	}

}
