package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowactivityinformation generated by hbm2java
 */
public class Workflowactivityinformation implements java.io.Serializable {

	private Integer id;
	private Integer workflowId;
	private Integer activityId;
	private String activityName;
	private Short layer;
	private Integer parentId;
	private Boolean isComposite;
	private String description;
	private boolean choiceManager;
	private Short activityType;
	private Short activityImplementation;
	private Float startTime;
	private Float duration;
	private Short iconId;
	private String activityUrl;
	private Short multiPersonMode;
	private Short submitPersonNumber;
	private Integer twcid;
	private Boolean isCallback;
	private String objectList;

	public Workflowactivityinformation() {
	}

	public Workflowactivityinformation(boolean choiceManager) {
		this.choiceManager = choiceManager;
	}

	public Workflowactivityinformation(Integer workflowId, Integer activityId, String activityName, Short layer,
			Integer parentId, Boolean isComposite, String description, boolean choiceManager, Short activityType,
			Short activityImplementation, Float startTime, Float duration, Short iconId, String activityUrl,
			Short multiPersonMode, Short submitPersonNumber, Integer twcid, Boolean isCallback, String objectList) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.activityName = activityName;
		this.layer = layer;
		this.parentId = parentId;
		this.isComposite = isComposite;
		this.description = description;
		this.choiceManager = choiceManager;
		this.activityType = activityType;
		this.activityImplementation = activityImplementation;
		this.startTime = startTime;
		this.duration = duration;
		this.iconId = iconId;
		this.activityUrl = activityUrl;
		this.multiPersonMode = multiPersonMode;
		this.submitPersonNumber = submitPersonNumber;
		this.twcid = twcid;
		this.isCallback = isCallback;
		this.objectList = objectList;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public Short getLayer() {
		return this.layer;
	}

	public void setLayer(Short layer) {
		this.layer = layer;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Boolean getIsComposite() {
		return this.isComposite;
	}

	public void setIsComposite(Boolean isComposite) {
		this.isComposite = isComposite;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isChoiceManager() {
		return this.choiceManager;
	}

	public void setChoiceManager(boolean choiceManager) {
		this.choiceManager = choiceManager;
	}

	public Short getActivityType() {
		return this.activityType;
	}

	public void setActivityType(Short activityType) {
		this.activityType = activityType;
	}

	public Short getActivityImplementation() {
		return this.activityImplementation;
	}

	public void setActivityImplementation(Short activityImplementation) {
		this.activityImplementation = activityImplementation;
	}

	public Float getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Float startTime) {
		this.startTime = startTime;
	}

	public Float getDuration() {
		return this.duration;
	}

	public void setDuration(Float duration) {
		this.duration = duration;
	}

	public Short getIconId() {
		return this.iconId;
	}

	public void setIconId(Short iconId) {
		this.iconId = iconId;
	}

	public String getActivityUrl() {
		return this.activityUrl;
	}

	public void setActivityUrl(String activityUrl) {
		this.activityUrl = activityUrl;
	}

	public Short getMultiPersonMode() {
		return this.multiPersonMode;
	}

	public void setMultiPersonMode(Short multiPersonMode) {
		this.multiPersonMode = multiPersonMode;
	}

	public Short getSubmitPersonNumber() {
		return this.submitPersonNumber;
	}

	public void setSubmitPersonNumber(Short submitPersonNumber) {
		this.submitPersonNumber = submitPersonNumber;
	}

	public Integer getTwcid() {
		return this.twcid;
	}

	public void setTwcid(Integer twcid) {
		this.twcid = twcid;
	}

	public Boolean getIsCallback() {
		return this.isCallback;
	}

	public void setIsCallback(Boolean isCallback) {
		this.isCallback = isCallback;
	}

	public String getObjectList() {
		return this.objectList;
	}

	public void setObjectList(String objectList) {
		this.objectList = objectList;
	}

}
