package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowprocessecarule generated by hbm2java
 */
public class Workflowprocessecarule implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int ruleId;
	private int eventId;
	private int conditionId;
	private String actionExpression;
	private Float probability;
	private Float probabilityCoefficient;

	public Workflowprocessecarule() {
	}

	public Workflowprocessecarule(int workflowId, int ruleId, int eventId, int conditionId) {
		this.workflowId = workflowId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
	}

	public Workflowprocessecarule(int workflowId, int ruleId, int eventId, int conditionId, String actionExpression,
			Float probability, Float probabilityCoefficient) {
		this.workflowId = workflowId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
		this.actionExpression = actionExpression;
		this.probability = probability;
		this.probabilityCoefficient = probabilityCoefficient;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public int getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(int conditionId) {
		this.conditionId = conditionId;
	}

	public String getActionExpression() {
		return this.actionExpression;
	}

	public void setActionExpression(String actionExpression) {
		this.actionExpression = actionExpression;
	}

	public Float getProbability() {
		return this.probability;
	}

	public void setProbability(Float probability) {
		this.probability = probability;
	}

	public Float getProbabilityCoefficient() {
		return this.probabilityCoefficient;
	}

	public void setProbabilityCoefficient(Float probabilityCoefficient) {
		this.probabilityCoefficient = probabilityCoefficient;
	}

}
