package cn.edu.sjtu.iasdsp.model;
// Generated 2017-7-5 20:36:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Workflowprocessecarule generated by hbm2java
 */
@Entity
@Table(name = "workflowprocessecarule", catalog = "isdsp_dev")
public class Workflowprocessecarule implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int ruleId;
	private int eventId;
	private int conditionId;
	private String actionExpression;
	private Float probability;
	private Float probabilityCoefficient;

	public Workflowprocessecarule() {
	}

	public Workflowprocessecarule(int workflowId, int ruleId, int eventId, int conditionId) {
		this.workflowId = workflowId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
	}

	public Workflowprocessecarule(int workflowId, int ruleId, int eventId, int conditionId, String actionExpression,
			Float probability, Float probabilityCoefficient) {
		this.workflowId = workflowId;
		this.ruleId = ruleId;
		this.eventId = eventId;
		this.conditionId = conditionId;
		this.actionExpression = actionExpression;
		this.probability = probability;
		this.probabilityCoefficient = probabilityCoefficient;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "WorkflowID", nullable = false)
	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "RuleID", nullable = false)
	public int getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	@Column(name = "EventID", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "ConditionID", nullable = false)
	public int getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(int conditionId) {
		this.conditionId = conditionId;
	}

	@Column(name = "ActionExpression", length = 200)
	public String getActionExpression() {
		return this.actionExpression;
	}

	public void setActionExpression(String actionExpression) {
		this.actionExpression = actionExpression;
	}

	@Column(name = "Probability", precision = 12, scale = 0)
	public Float getProbability() {
		return this.probability;
	}

	public void setProbability(Float probability) {
		this.probability = probability;
	}

	@Column(name = "ProbabilityCoefficient", precision = 12, scale = 0)
	public Float getProbabilityCoefficient() {
		return this.probabilityCoefficient;
	}

	public void setProbabilityCoefficient(Float probabilityCoefficient) {
		this.probabilityCoefficient = probabilityCoefficient;
	}

}
