package cn.edu.sjtu.iasdsp.model;
// Generated 2017-6-26 3:55:41 by Hibernate Tools 5.2.3.Final

/**
 * Workflowactivityinvokingapplication generated by hbm2java
 */
public class Workflowactivityinvokingapplication implements java.io.Serializable {

	private Integer id;
	private int workflowId;
	private int activityId;
	private int applicationId;
	private Short invocationType;
	private Integer inputSchemaId;
	private Integer outputSchemaId;

	public Workflowactivityinvokingapplication() {
	}

	public Workflowactivityinvokingapplication(int workflowId, int activityId, int applicationId) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.applicationId = applicationId;
	}

	public Workflowactivityinvokingapplication(int workflowId, int activityId, int applicationId, Short invocationType,
			Integer inputSchemaId, Integer outputSchemaId) {
		this.workflowId = workflowId;
		this.activityId = activityId;
		this.applicationId = applicationId;
		this.invocationType = invocationType;
		this.inputSchemaId = inputSchemaId;
		this.outputSchemaId = outputSchemaId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public Short getInvocationType() {
		return this.invocationType;
	}

	public void setInvocationType(Short invocationType) {
		this.invocationType = invocationType;
	}

	public Integer getInputSchemaId() {
		return this.inputSchemaId;
	}

	public void setInputSchemaId(Integer inputSchemaId) {
		this.inputSchemaId = inputSchemaId;
	}

	public Integer getOutputSchemaId() {
		return this.outputSchemaId;
	}

	public void setOutputSchemaId(Integer outputSchemaId) {
		this.outputSchemaId = outputSchemaId;
	}

}
